In [1]:
import pandas as pd
import numpy as np
import time
import warnings
warnings.simplefilter("ignore", UserWarning)

## Import Rec vs Work (from Download )

In [2]:
start_time = time.time()

rec_vs_work = pd.read_excel(
    r'C:\Users\IN10052060\Desktop\Received VS Worked Master File.xlsx',
    sheet_name='UniqeData'
)

end_time = time.time()
elapsed_time = end_time - start_time

print(f"File loaded in {elapsed_time:.2f} seconds")

File loaded in 89.92 seconds

rec_vs_work.columns = rec_vs_work.iloc[0]

rec_vs_work = rec_vs_work[1:].reset_index(drop=True)

In [3]:
rec_vs_work.isna().sum()

Unique                    0
Drill TYPE                0
Project Name              0
FacilityGroupName        54
FacilityCode             14
                      ...
Rsn_Cd5              138908
Amt5                 138908
Grp_Cd6              139630
Rsn_Cd6              139630
Amt6                 139630
Length: 82, dtype: int64

In [4]:
rec_vs_work.shape

(139706, 82)

In [5]:
rec_vs_work.dropna(subset = ['Unique'], inplace = True)

In [6]:
rec_vs_work.shape

(139706, 82)

In [7]:
rec_vs_work[rec_vs_work['Group'].isna()]

,Unique,Drill TYPE,Project Name,FacilityGroupName,FacilityCode,EncounterID,Group,Status,Final Status,Date,...,Amt3,Grp_Cd4,Rsn_Cd4,Amt4,Grp_Cd5,Rsn_Cd5,Amt5,Grp_Cd6,Rsn_Cd6,Amt6
69035,ABCD123456789,Contractual,ARMT 2B Part 6- Total Payment +Bad Debt > Prim...,NaN,ABCD,123456789,NaN,N,NaN,6/16/2026-1:49:11 PM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
71107,BOLE0006050820352,Contractual,Beacon Expected Met,Borgess,BOLE,0006050820352,NaN,N,NaN,6/16/2026-2:55:57 PM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
71108,BOMC0013813300061,Contractual,Beacon Expected Met,Borgess,BOMC,0013813300061,NaN,N,NaN,6/16/2026-2:55:57 PM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
71109,BOMC0002112960021,Contractual,Beacon Expected Met,Borgess,BOMC,0002112960021,NaN,N,NaN,6/16/2026-2:55:57 PM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
71110,BOMC0007530230156,Contractual,Beacon Expected Met,Borgess,BOMC,0007530230156,NaN,N,NaN,6/16/2026-2:55:57 PM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138833,QMNV2100745,Patient Billing,ARMT 1C,Quorum,QMNV,2100745,NaN,NaN,NaN,6/19/2026-10:21:40 PM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
138834,QMNV2218131,Patient Billing,ARMT 1C,Quorum,QMNV,2218131,NaN,NaN,NaN,6/19/2026-10:21:40 PM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
138835,QMNV2220512,Patient Billing,ARMT 1C,Quorum,QMNV,2220512,NaN,NaN,NaN,6/19/2026-10:21:40 PM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
138836,QRKY3198321,Patient Billing,ARMT 1C,Quorum,QRKY,3198321,NaN,NaN,NaN,6/19/2026-10:21:40 PM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
138837,QTKY6325224,Patient Billing,ARMT 1C,Quorum,QTKY,6325224,NaN,NaN,NaN,6/19/2026-10:21:40 PM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
rec_vs_work.isna().sum()

Unique                    0
Drill TYPE                0
Project Name              0
FacilityGroupName        54
FacilityCode             14
                      ...
Rsn_Cd5              138908
Amt5                 138908
Grp_Cd6              139630
Rsn_Cd6              139630
Amt6                 139630
Length: 82, dtype: int64

In [9]:
col = ['Unique', 'Drill TYPE', 'Project Name', 'FacilityGroupName', 'FacilityCode', 'EncounterID', 'Encounter Insurance Balance',
      'EncounterPatientBalance', 'EncounterOpenBalance', 'Current Payer Plan Code', 'Current Major Payor', 
      'Encounter Insurance Balance.1', 'Group', 'Primary Payer Plan Code', 'Secondary Payer Plan Code']

In [10]:
rec_vs_work.columns

Index(['Unique', 'Drill TYPE', 'Project Name', 'FacilityGroupName',
       'FacilityCode', 'EncounterID', 'Group', 'Status', 'Final Status',
       'Date', 'TB Control', 'Encounter Insurance Balance', 'Current Balance',
       'Transacted $', 'Phase', 'DFD', 'Repetitive', 'EncounterTotalCharges',
       'EncounterPatientBalance', 'EncounterOpenBalance',
       'Primary Payer Plan Code', 'Secondary Payer Plan Code',
       'Primary Payer Plan Name', 'WRITEOFF', 'EncounterID.1', 'dsfd',
       'AdmitDate', 'DischargeDate', 'DFD.1', 'M7', 'Reado', 'Repetitive.1',
       'Rev code /CPT charges/GZ/MN', 'Primary Patient responsibility',
       'Secondary Patient Responsibility', 'R1D Expected ',
       'Secondary Payer Plan Name', 'Current Payer Plan Code',
       'Current Payer Plan Name', 'Tertiary Payer Plan Code',
       'Tertiary Payer Plan Name', 'Primary Major Payor',
       'Secondary Major Payor', 'Tertiary Major Payor', 'Current Major Payor',
       'Encounter Insurance Balance.1', 'Encounter Patient Balance',
       'Encounter Open Balance', 'Username', 'ActivityCode', 'Check',
       'Claim Status', 'Work Allocation', 'Drill Category', 'Repititive_Week2',
       'Repititive', 'Actual repetitive', 'Repititive/fresh', 'T code',
       'Mass update', 'StandardPatientType', 'Emp ID', 'Next Follow Date',
       'InvoiceNumber', 'Grp_Cd1', 'Rsn_Cd1', 'Amt1', 'Grp_Cd2', 'Rsn_Cd2',
       'Amt2', 'Grp_Cd3', 'Rsn_Cd3', 'Amt3', 'Grp_Cd4', 'Rsn_Cd4', 'Amt4',
       'Grp_Cd5', 'Rsn_Cd5', 'Amt5', 'Grp_Cd6', 'Rsn_Cd6', 'Amt6'],
      dtype='object')

In [11]:
df = rec_vs_work[col]

In [12]:
df.shape

(139706, 15)

In [13]:
df = df.copy()
df['EncounterID'] = df['EncounterID'].astype(str).str.lstrip('0')

In [14]:
df['EncounterID'].isna().sum()

np.int64(0)

In [15]:
df.shape

(139706, 15)

In [16]:
df = df.copy()
df['PN'] = df['Project Name'].str.strip().str.lower()

In [17]:
df['Unique'] = df['FacilityCode'].astype(str) + df['EncounterID'].astype(str)

In [18]:
df['Key'] = df['FacilityCode'].astype(str) + df['EncounterID'].astype(str) + df['PN'].astype(str)

In [19]:
# Update the balance in existing df
start_time = time.time()

Update_bal = pd.read_excel(r"C:\Users\IN10052060\OneDrive - R1\Target Balance support\Balance Output.xlsx", sheet_name = 'UniqeData')

end_time = time.time()
elapsed_time = end_time - start_time

print(f"File loaded in {elapsed_time:.2f} seconds")

File loaded in 48.85 seconds

In [20]:
Update_bal.head()

,Facilitycode,EncounterID,id,CurrentFinancialClass,EncounterInsuranceBalance,EncounterOpenBalance,EncounterPatientBalance,EncounterTotalCharges,CurrentMajoryPayer,CurrentPayorPlanCode,...,UserID,Username,ActivityCode,act_date_2,Username2,ActivityCode2,act_date_3,Username3,ActivityCode3,SourceFile
0,BYFL,87005773392,1033888,6105,72.00,72.00,0.0,2647.00,BLUE CROSS,610500000,...,57011.0,SGURANG1,Qualified for TB Drill,2026-06-15 14:46:57.500,r1a4,Balance Transferred from Primary to Secondary,2026-06-05 07:09:22.887,skumar930,Demanded Secondary Claim From Host,sql_chunk_10_20260619-203037.xlsx
1,BYFL,87005790974,1035681,3096,32.33,32.33,0.0,4437.00,COMMERCIAL/HMO,309600000,...,57011.0,SGURANG1,Qualified for TB Drill,2026-06-15 14:51:20.233,r1a4,Balance Transferred from Primary to Secondary,2026-05-11 09:39:33.237,SGURANG1,Qualified for TB Drill,sql_chunk_10_20260619-203037.xlsx
2,BYFL,87005792970,1035881,6105,38714.85,38714.85,0.0,177932.30,BLUE CROSS,610500000,...,122460.0,R1D_Palantir,NaN,2026-06-11 04:57:48.087,NaN,NaN,2026-06-10 21:58:09.140,KHaun11,NaN,sql_chunk_10_20260619-203037.xlsx
3,BYFL,87005920498,1048904,3035,108.64,108.64,0.0,3899.88,COMMERCIAL/HMO,303500000,...,57011.0,SGURANG1,Qualified for TB Drill,2026-06-15 14:46:51.853,r1a4,Balance Transferred from Primary to Secondary,2026-04-26 09:10:54.680,NaN,NaN,sql_chunk_10_20260619-203037.xlsx
4,BYFL,87005921058,1048960,4803,1050.00,1050.00,0.0,17521.25,AUTO/WC,480300000,...,57011.0,SGURANG1,Qualified for TB Drill,2026-06-15 14:47:40.940,r1a4,Balance Transferred from Primary to Secondary,2026-05-03 09:11:38.617,NaN,NaN,sql_chunk_10_20260619-203037.xlsx

In [21]:
Update_bal.shape

(137149, 24)

In [22]:
Update_bal.columns

Index(['Facilitycode', 'EncounterID', 'id', 'CurrentFinancialClass',
       'EncounterInsuranceBalance', 'EncounterOpenBalance',
       'EncounterPatientBalance', 'EncounterTotalCharges',
       'CurrentMajoryPayer', 'CurrentPayorPlanCode', 'CreatedDateTime',
       'ScheduleDateTime', 'Createdby', 'Note', 'UserID', 'Username',
       'ActivityCode', 'act_date_2', 'Username2', 'ActivityCode2',
       'act_date_3', 'Username3', 'ActivityCode3', 'SourceFile'],
      dtype='object')

In [23]:
col = ['Facilitycode', 'EncounterID', 'CurrentFinancialClass', 'EncounterInsuranceBalance',
       'EncounterOpenBalance', 'EncounterPatientBalance', 'ActivityCode' ,
       'CurrentMajoryPayer', 'CurrentPayorPlanCode', 'EncounterTotalCharges', 'ActivityCode2', 'ActivityCode3']
Update_bal = Update_bal[col]

In [24]:
Update_bal['EncounterID'] = Update_bal['EncounterID'].astype(str).str.lstrip('0')

In [25]:
Update_bal['Uni'] = Update_bal['Facilitycode'].astype(str) + Update_bal['EncounterID'].astype(str)

In [26]:
Update_bal.drop_duplicates(subset = 'Uni', inplace = True)

In [27]:
Update_bal.shape

(137121, 13)

In [28]:
Update_bal.shape

(137121, 13)

In [29]:
df.shape

(139706, 17)

In [30]:
last_week = df.merge(Update_bal, how = 'left', left_on = 'Unique', right_on = 'Uni')
last_week.head()

,Unique,Drill TYPE,Project Name,FacilityGroupName,FacilityCode,EncounterID_x,Encounter Insurance Balance,EncounterPatientBalance_x,EncounterOpenBalance_x,Current Payer Plan Code,...,EncounterInsuranceBalance,EncounterOpenBalance_y,EncounterPatientBalance_y,ActivityCode,CurrentMajoryPayer,CurrentPayorPlanCode,EncounterTotalCharges,ActivityCode2,ActivityCode3,Uni
0,FNWI40013277560,Contractual,CO-253 Sequestration,Wheaton,FNWI,40013277560,2.19,0.0,2.19,160030011,...,0.0,0.0,0.0,Qualified for TB Drill,COMMERCIAL/HMO,160030011,530.00,NaN,NaN,FNWI40013277560
1,GRMC10009536020,Contractual,CO-253 Sequestration,Flint,GRMC,10009536020,6.92,0.0,6.92,D37,...,0.0,0.0,0.0,ePARS: Cash Posting Response,BLUE CROSS,D37,1900.00,Applied Contractual/Adjustment,Qualified for TB Drill,GRMC10009536020
2,EKWI31002766923,Contractual,CO-253 Sequestration,Milwaukee,EKWI,31002766923,0.56,0.0,0.56,10100013,...,0.0,0.0,0.0,NaN,MEDICAREHMO,10100013,275.00,Qualified for TB Drill,Contractual/Adjustment Applied,EKWI31002766923
3,FNWI40013180146,Contractual,CO-253 Sequestration,Wheaton,FNWI,40013180146,33.23,0.0,33.23,10200046,...,0.0,0.0,0.0,Qualified for TB Drill,COMMERCIAL/HMO,10200046,2663.09,NaN,Confirmed Payment is Promised,FNWI40013180146
4,FNWI40013208703,Contractual,CO-253 Sequestration,Wheaton,FNWI,40013208703,2.18,0.0,2.18,16015701,...,0.0,0.0,0.0,Qualified for TB Drill,MEDICAREHMO,16015701,292.00,NaN,NaN,FNWI40013208703

In [31]:
last_week.shape

(139706, 30)

In [32]:
last_week.columns

Index(['Unique', 'Drill TYPE', 'Project Name', 'FacilityGroupName',
       'FacilityCode', 'EncounterID_x', 'Encounter Insurance Balance',
       'EncounterPatientBalance_x', 'EncounterOpenBalance_x',
       'Current Payer Plan Code', 'Current Major Payor',
       'Encounter Insurance Balance.1', 'Group', 'Primary Payer Plan Code',
       'Secondary Payer Plan Code', 'PN', 'Key', 'Facilitycode',
       'EncounterID_y', 'CurrentFinancialClass', 'EncounterInsuranceBalance',
       'EncounterOpenBalance_y', 'EncounterPatientBalance_y', 'ActivityCode',
       'CurrentMajoryPayer', 'CurrentPayorPlanCode', 'EncounterTotalCharges',
       'ActivityCode2', 'ActivityCode3', 'Uni'],
      dtype='object')

In [33]:
last_week.rename({'EncounterID_x':'EncounterID', 'EncounterPatientBalance_x':'EncounterPatientBalance', 
                 'EncounterOpenBalance_x':'EncounterOpenBalance', 'Encounter Insurance Balance.1' : 'Encounter Insurance Balance IM',
                 'EncounterOpenBalance_y' : 'EncounterOpenBalance U', 'EncounterPatientBalance_y': 'EncounterPatientBalance U',
                 'ActivityCode': 'ActivityCode U', 'CurrentPayorPlanCode' : 'CurrentPPC', 'EncounterInsuranceBalance':'EncounterInsuranceBalance U', 
                 'CurrentFinancialClass': 'CurrentFinancialClass U', 
                 'EncounterTotalCharges': 'EncounterTotalCharges U'}, axis = 1, inplace = True)

In [34]:
last_week.isna().sum()

Unique                                 0
Drill TYPE                             0
Project Name                           0
FacilityGroupName                     54
FacilityCode                          14
EncounterID                            0
Encounter Insurance Balance           60
EncounterPatientBalance               85
EncounterOpenBalance                  76
Current Payer Plan Code            46460
Current Major Payor                88158
Encounter Insurance Balance IM     30922
Group                               4871
Primary Payer Plan Code            47321
Secondary Payer Plan Code         110631
PN                                     0
Key                                    0
Facilitycode                         364
EncounterID_y                        364
CurrentFinancialClass U              695
EncounterInsuranceBalance U          364
EncounterOpenBalance U               364
EncounterPatientBalance U            364
ActivityCode U                     18042
CurrentMajoryPayer                  3502
CurrentPPC                          1326
EncounterTotalCharges U              364
ActivityCode2                      34790
ActivityCode3                      80192
Uni                                  364
dtype: int64

In [35]:
last_week['ActivityCode U'] = (
    last_week['ActivityCode U']
    .str.replace(
        r'(?i)(one|1)\s*week[s]?\s*review\s*required',
        'One week review required',
        regex=True
    )
)

In [36]:
last_week[last_week['Project Name'] == 'Ascension- NSA: Without 835 PR']['ActivityCode U'].unique()

array(['Qualified for TB Drill',
       'Account updated for same day follow up.',
       'One week review required',
       'Balance Transferred from Patient to Insurance', nan,
       'WriteOff category-Non-Covered',
       'Confirmed Patient Balance is Appropriate'], dtype=object)

In [37]:
merge_df = last_week.copy()

In [38]:
merge_df.shape

(139706, 30)

In [39]:
merge_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 139706 entries, 0 to 139705
Data columns (total 30 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   Unique                          139706 non-null  object
 1   Drill TYPE                      139706 non-null  object
 2   Project Name                    139706 non-null  object
 3   FacilityGroupName               139652 non-null  object
 4   FacilityCode                    139692 non-null  object
 5   EncounterID                     139706 non-null  object
 6   Encounter Insurance Balance     139646 non-null  float64
 7   EncounterPatientBalance         139621 non-null  float64
 8   EncounterOpenBalance            139630 non-null  float64
 9   Current Payer Plan Code         93246 non-null   object
 10  Current Major Payor             51548 non-null   object
 11  Encounter Insurance Balance IM  108784 non-null  float64
 12  Group                           134835 non-null  float64
 13  Primary Payer Plan Code         92385 non-null   object
 14  Secondary Payer Plan Code       29075 non-null   object
 15  PN                              139706 non-null  object
 16  Key                             139706 non-null  object
 17  Facilitycode                    139342 non-null  object
 18  EncounterID_y                   139342 non-null  object
 19  CurrentFinancialClass U         139011 non-null  object
 20  EncounterInsuranceBalance U     139342 non-null  float64
 21  EncounterOpenBalance U          139342 non-null  float64
 22  EncounterPatientBalance U       139342 non-null  float64
 23  ActivityCode U                  121664 non-null  object
 24  CurrentMajoryPayer              136204 non-null  object
 25  CurrentPPC                      138380 non-null  object
 26  EncounterTotalCharges U         139342 non-null  float64
 27  ActivityCode2                   104916 non-null  object
 28  ActivityCode3                   59514 non-null   object
 29  Uni                             139342 non-null  object
dtypes: float64(9), object(21)
memory usage: 32.0+ MB

In [40]:
merge_df['Group'].unique()

array([ 2., 30.,  1.,  3.,  8.,  4., 13., 42.,  9., 11., 21.,  5., 35.,
       nan, 22., 12., 16., 14., 28., 40., 29., 37., 32.])

In [41]:
merge_df = merge_df.copy()

In [42]:
merge_df['Group'] = merge_df['Group'].fillna(0).astype(int)

In [43]:
merge_df['Group'].unique()

array([ 2, 30,  1,  3,  8,  4, 13, 42,  9, 11, 21,  5, 35,  0, 22, 12, 16,
       14, 28, 40, 29, 37, 32])

In [44]:
merge_df.columns

Index(['Unique', 'Drill TYPE', 'Project Name', 'FacilityGroupName',
       'FacilityCode', 'EncounterID', 'Encounter Insurance Balance',
       'EncounterPatientBalance', 'EncounterOpenBalance',
       'Current Payer Plan Code', 'Current Major Payor',
       'Encounter Insurance Balance IM', 'Group', 'Primary Payer Plan Code',
       'Secondary Payer Plan Code', 'PN', 'Key', 'Facilitycode',
       'EncounterID_y', 'CurrentFinancialClass U',
       'EncounterInsuranceBalance U', 'EncounterOpenBalance U',
       'EncounterPatientBalance U', 'ActivityCode U', 'CurrentMajoryPayer',
       'CurrentPPC', 'EncounterTotalCharges U', 'ActivityCode2',
       'ActivityCode3', 'Uni'],
      dtype='object')

In [45]:
VBR = pd.read_excel(r"C:\Users\IN10052060\OneDrive - R1\Dashboard\Last Week Report\Last Week Report\VBR.xlsx", sheet_name = 'Raw Data')
VBR.head()

Empty DataFrame
Columns: [Facilitycode, EncounterID, Current Financial Class]
Index: []

In [46]:
col = ['Facilitycode', 'EncounterID', 'Current Financial Class']
VBR = VBR[col]

In [47]:
VBR.shape

(0, 3)

In [48]:
VBR = VBR.copy()
VBR['EncounterID'] = VBR['EncounterID'].astype(str).str.lstrip('0')

In [49]:
VBR['Uni'] = VBR['Facilitycode'].astype(str) + VBR['EncounterID'].astype(str)

In [50]:
VBR.drop_duplicates(subset = 'Uni', inplace = True)

Empty DataFrame
Columns: [Facilitycode, EncounterID, Current Financial Class, Uni]
Index: []

In [51]:
Final_df = merge_df.merge(VBR, how = 'left', left_on = 'Unique' , right_on = 'Uni')

In [52]:
Final_df

,Unique,Drill TYPE,Project Name,FacilityGroupName,FacilityCode,EncounterID_x,Encounter Insurance Balance,EncounterPatientBalance,EncounterOpenBalance,Current Payer Plan Code,...,CurrentMajoryPayer,CurrentPPC,EncounterTotalCharges U,ActivityCode2,ActivityCode3,Uni_x,Facilitycode_y,EncounterID_y,Current Financial Class,Uni_y
0,FNWI40013277560,Contractual,CO-253 Sequestration,Wheaton,FNWI,40013277560,2.19,0.0,2.19,160030011,...,COMMERCIAL/HMO,160030011,530.00,NaN,NaN,FNWI40013277560,NaN,NaN,NaN,NaN
1,GRMC10009536020,Contractual,CO-253 Sequestration,Flint,GRMC,10009536020,6.92,0.0,6.92,D37,...,BLUE CROSS,D37,1900.00,Applied Contractual/Adjustment,Qualified for TB Drill,GRMC10009536020,NaN,NaN,NaN,NaN
2,EKWI31002766923,Contractual,CO-253 Sequestration,Milwaukee,EKWI,31002766923,0.56,0.0,0.56,10100013,...,MEDICAREHMO,10100013,275.00,Qualified for TB Drill,Contractual/Adjustment Applied,EKWI31002766923,NaN,NaN,NaN,NaN
3,FNWI40013180146,Contractual,CO-253 Sequestration,Wheaton,FNWI,40013180146,33.23,0.0,33.23,10200046,...,COMMERCIAL/HMO,10200046,2663.09,NaN,Confirmed Payment is Promised,FNWI40013180146,NaN,NaN,NaN,NaN
4,FNWI40013208703,Contractual,CO-253 Sequestration,Wheaton,FNWI,40013208703,2.18,0.0,2.18,16015701,...,MEDICAREHMO,16015701,292.00,NaN,NaN,FNWI40013208703,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
139701,A1221281484421,Write off,Write-Offs,Intermountain Health,A122,1281484421,1001.07,0.0,1001.07,NaN,...,COMMERCIAL/HMO,5050,3820.91,Confirmed Payment is Promised,Sent Inquiry to Payer (Email/Online) - 7 Days,A1221281484421,NaN,NaN,NaN,NaN
139702,A1381279727343-1,Write off,Write-Offs,Intermountain Health,A138,1279727343-1,1000.63,0.0,1000.63,NaN,...,COMMERCIAL/HMO,5050,1000.63,System action taken to reset account age,NaN,A1381279727343-1,NaN,NaN,NaN,NaN
139703,A1441279875282,Write off,Write-Offs,Intermountain Health,A144,1279875282,1000.03,0.0,1000.03,NaN,...,COMMERCIAL/HMO,1916,2557.60,System action taken to reset account age,System action taken to reset account age,A1441279875282,NaN,NaN,NaN,NaN
139704,A1391279965663,Write off,Write-Offs,Intermountain Health,A139,1279965663,1000.00,0.0,1000.00,NaN,...,COMMERCIAL/HMO,4712,9682.00,System action taken to reset account age,Transferred Bal to Patient Per Hospital Guidel...,A1391279965663,NaN,NaN,NaN,NaN
139705,A2701278125259-2,Write off,Write-Offs,Intermountain Health,A270,1278125259-2,1000.00,0.0,1000.00,NaN,...,COMMERCIAL/HMO,5037,1000.00,Sent inquiry to payer (Email/Online) -15 Days,NaN,A2701278125259-2,NaN,NaN,NaN,NaN

In [53]:
Final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 139706 entries, 0 to 139705
Data columns (total 34 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   Unique                          139706 non-null  object
 1   Drill TYPE                      139706 non-null  object
 2   Project Name                    139706 non-null  object
 3   FacilityGroupName               139652 non-null  object
 4   FacilityCode                    139692 non-null  object
 5   EncounterID_x                   139706 non-null  object
 6   Encounter Insurance Balance     139646 non-null  float64
 7   EncounterPatientBalance         139621 non-null  float64
 8   EncounterOpenBalance            139630 non-null  float64
 9   Current Payer Plan Code         93246 non-null   object
 10  Current Major Payor             51548 non-null   object
 11  Encounter Insurance Balance IM  108784 non-null  float64
 12  Group                           139706 non-null  int64
 13  Primary Payer Plan Code         92385 non-null   object
 14  Secondary Payer Plan Code       29075 non-null   object
 15  PN                              139706 non-null  object
 16  Key                             139706 non-null  object
 17  Facilitycode_x                  139342 non-null  object
 18  EncounterID_y                   139342 non-null  object
 19  CurrentFinancialClass U         139011 non-null  object
 20  EncounterInsuranceBalance U     139342 non-null  float64
 21  EncounterOpenBalance U          139342 non-null  float64
 22  EncounterPatientBalance U       139342 non-null  float64
 23  ActivityCode U                  121664 non-null  object
 24  CurrentMajoryPayer              136204 non-null  object
 25  CurrentPPC                      138380 non-null  object
 26  EncounterTotalCharges U         139342 non-null  float64
 27  ActivityCode2                   104916 non-null  object
 28  ActivityCode3                   59514 non-null   object
 29  Uni_x                           139342 non-null  object
 30  Facilitycode_y                  0 non-null       object
 31  EncounterID_y                   0 non-null       object
 32  Current Financial Class         0 non-null       object
 33  Uni_y                           0 non-null       object
dtypes: float64(8), int64(1), object(25)
memory usage: 36.2+ MB

In [54]:
Final_df.shape

(139706, 34)

In [55]:
def validate_row(row):
    group = row['Group']
    PN  = row['Project Name']
    FGN = row['FacilityGroupName']
    

    if group != 24 and pd.isnull(row['EncounterInsuranceBalance U']):
        return "Couldn't fetch the data"  
        
    elif (
    row['EncounterInsuranceBalance U'] == 0 and
    row['EncounterOpenBalance U'] == 0 and
    row['EncounterPatientBalance U'] == 0
    ):
        return "Transacted"
    
    elif group == 0:   # Actually Blank in Group column 
        return "Validation Mapping Error"
    
    elif group == 1 and row['EncounterOpenBalance U'] != row['EncounterOpenBalance']:
        return "Transacted"
    elif group == 2 and row['EncounterInsuranceBalance U'] != row['Encounter Insurance Balance']:
        return "Transacted"
    elif group == 3 and row['EncounterInsuranceBalance U'] == 0:
        return "Transacted"
    elif group == 4 and row['EncounterOpenBalance U'] == 0:
        return "Transacted"
    elif group == 5 and row['EncounterPatientBalance U'] == 0:
        return "Transacted"
    elif group == 6 and row['EncounterPatientBalance U'] == 0:
        return "Transacted"
    elif group == 7 and (row['EncounterInsuranceBalance U'] != row['Encounter Insurance Balance'] 
                         or row['CurrentPPC'] != row['Current Payer Plan Code']):
        return "Transacted"
    elif group == 8 and (
        row['EncounterOpenBalance U'] != row['EncounterOpenBalance'] or 
        isinstance(row['ActivityCode U'], str) and "Write" in row['ActivityCode U']
    ):
        return "Transacted"
    elif group == 9 and (
        row['EncounterOpenBalance U'] != row['EncounterOpenBalance'] or 
        row['EncounterInsuranceBalance U'] == 0
    ):
        return "Transacted"
    elif group == 10 and isinstance(row['ActivityCode U'], str) and row['ActivityCode U'].startswith("Write"):
        return "Transacted"
    elif group == 11 and row['CurrentMajoryPayer'] != row['Current Major Payor']:
        return "Transacted"
    elif group == 12 and (
        row['Current Financial Class'] != row['CurrentFinancialClass U'] or 
        row['EncounterInsuranceBalance U'] != row['Encounter Insurance Balance']
    ):
        return "Transacted"
    elif group == 13 and (
        row['CurrentMajoryPayer'] != row['Current Major Payor'] or 
        row['EncounterOpenBalance'] != row['EncounterOpenBalance U']
    ):
        return "Transacted"
    elif group == 14 and (
        row['CurrentMajoryPayer'] != "Medicare"
    ):
        return "Transacted"
    elif group == 15 and (
        row['EncounterInsuranceBalance U'] > 0 
    ):
        return "Transacted"
    elif group == 16 and row['EncounterPatientBalance'] != row['EncounterPatientBalance U']:
        return "Transacted"
    elif group == 17 and (
        row['EncounterInsuranceBalance U'] > 0 or  
        isinstance(row['ActivityCode U'], str) and "Account updated for same day follow up" in row['ActivityCode U']
    ):
        return "Transacted"

    elif group == 19 and row['CurrentPPC'] != row['Current Payer Plan Code']:
        return "Transacted"

    elif group == 20 and (row['CurrentMajoryPayer'] != row['Current Major Payor'] and row['CurrentPPC'] != row['Current Payer Plan Code']):
         return "Transacted"

    elif group == 21 and (
    (isinstance(row['ActivityCode U'], str) and "Account updated for same day follow up" in row['ActivityCode U']) or
    (isinstance(row['ActivityCode2'], str) and "Account updated for same day follow up" in row['ActivityCode2']) or
    (isinstance(row['ActivityCode3'], str) and "Account updated for same day follow up" in row['ActivityCode3']) or
    row['EncounterInsuranceBalance U'] > 0 or
    row['EncounterOpenBalance U'] != row['EncounterOpenBalance'] or
    row['EncounterOpenBalance U'] == 0
    ):
        
        return "Transacted"

    elif group == 23 and (
        row['EncounterOpenBalance U'] == 0 or 
        row['EncounterInsuranceBalance U'] == 0):
    
        return "Transacted"

    elif group == 24 and (
        row['Primary Payer Plan Code'] != row['Secondary Payer Plan Code']):
        return "Transacted"

    elif group == 25 and (
        row['EncounterOpenBalance U'] != row['EncounterOpenBalance'] and 
        row['EncounterInsuranceBalance U'] == 0
    ):
        return "Transacted"

    
    elif group == 26 and (
        row['EncounterOpenBalance U'] > 0
        
    ):
        return "Transacted"

    elif group == 27 and (
       row['EncounterOpenBalance U'] != row['EncounterOpenBalance'] or
       row['EncounterInsuranceBalance U'] != row['Encounter Insurance Balance']
    ):
        return "Transacted"

    elif group == 28 and FGN == "Lifepoint" and (
    row['EncounterInsuranceBalance U'] == 0 or
    row['EncounterOpenBalance U'] != row['EncounterOpenBalance']
    ):
        return "Transacted"

    elif group == 28 and FGN != "Lifepoint" and row['EncounterOpenBalance U'] == 0:
        return "Transacted"

    elif group == 29 and (
    row['EncounterPatientBalance U'] == 0 or 
    isinstance(row['ActivityCode U'], str) and 
    "One week review required" in row['ActivityCode U']
    ):
        return "Transacted"

    elif group == 30 and (
        row['EncounterOpenBalance U'] != row['EncounterOpenBalance'] or
        row['EncounterPatientBalance'] != row['EncounterPatientBalance U']
    ):
        return "Transacted"

    elif group == 31 and (
        row['EncounterOpenBalance U'] == 0 or
        row['EncounterInsuranceBalance U'] == 0
    ):
        return "Transacted"

    elif group == 32 and (
        row['EncounterTotalCharges U'] > 0
    ):
        return "Transacted"

    elif group == 33 and (
        row['EncounterOpenBalance U'] != row['EncounterOpenBalance'] or
        row['EncounterInsuranceBalance U'] != row['Encounter Insurance Balance'] or
        row['CurrentMajoryPayer'] != row['Current Major Payor']
    ):
        return "Transacted"

    elif group == 34 and (
        row['Current Financial Class'] != row['CurrentFinancialClass U']
    ):
        return "Transacted"

    elif group == 35 and (
        row['EncounterOpenBalance U'] != row['EncounterOpenBalance'] or
        row['EncounterInsuranceBalance U'] != row['Encounter Insurance Balance']
    ):
        return "Transacted"

    elif group == 36 and (
        row['EncounterOpenBalance U'] <= 0 or
        row['EncounterInsuranceBalance U'] == 0 
        
    ):
        return "Transacted"

    elif group == 37 and (
        row['EncounterInsuranceBalance U'] != row['Encounter Insurance Balance'] or 
        isinstance(row['ActivityCode U'], str) and "Unable to process claim until next day" in row['ActivityCode U']
    ):
        return "Transacted"

    elif group == 38 and (
        row['EncounterInsuranceBalance U'] != row['Encounter Insurance Balance'] or
        row['EncounterInsuranceBalance U'] == 0
    ):
        return "Transacted"

    elif group == 39 and (
        row['EncounterInsuranceBalance U'] != row['Encounter Insurance Balance'] or
        row['EncounterOpenBalance U'] != row['EncounterOpenBalance'] or
        row['Current Financial Class'] != row['CurrentFinancialClass U'] 
    ):
        return "Transacted"

    elif group == 40 and (
        row['EncounterInsuranceBalance U'] != row['Encounter Insurance Balance'] or
        row['EncounterOpenBalance U'] != row['EncounterOpenBalance'] or
        row['CurrentPPC'] != row['Current Payer Plan Code']
    ):
        return "Transacted"

    elif group == 41 and (
        row['EncounterInsuranceBalance U'] != row['Encounter Insurance Balance'] or
        row['CurrentMajoryPayer'] != row['Current Major Payor']
    ):
        return "Transacted"
        
    elif group == 42 and (
        row['EncounterInsuranceBalance U'] != row['Encounter Insurance Balance'] or
        row['CurrentPPC'] != row['Current Payer Plan Code']
    ):
        return "Transacted"
    
        
        
    return "Not Transacted"

# Apply to DataFrame
Final_df['Validation'] = Final_df.apply(validate_row, axis=1)

In [56]:
Final_df.head()

,Unique,Drill TYPE,Project Name,FacilityGroupName,FacilityCode,EncounterID_x,Encounter Insurance Balance,EncounterPatientBalance,EncounterOpenBalance,Current Payer Plan Code,...,CurrentPPC,EncounterTotalCharges U,ActivityCode2,ActivityCode3,Uni_x,Facilitycode_y,EncounterID_y,Current Financial Class,Uni_y,Validation
0,FNWI40013277560,Contractual,CO-253 Sequestration,Wheaton,FNWI,40013277560,2.19,0.0,2.19,160030011,...,160030011,530.00,NaN,NaN,FNWI40013277560,NaN,NaN,NaN,NaN,Transacted
1,GRMC10009536020,Contractual,CO-253 Sequestration,Flint,GRMC,10009536020,6.92,0.0,6.92,D37,...,D37,1900.00,Applied Contractual/Adjustment,Qualified for TB Drill,GRMC10009536020,NaN,NaN,NaN,NaN,Transacted
2,EKWI31002766923,Contractual,CO-253 Sequestration,Milwaukee,EKWI,31002766923,0.56,0.0,0.56,10100013,...,10100013,275.00,Qualified for TB Drill,Contractual/Adjustment Applied,EKWI31002766923,NaN,NaN,NaN,NaN,Transacted
3,FNWI40013180146,Contractual,CO-253 Sequestration,Wheaton,FNWI,40013180146,33.23,0.0,33.23,10200046,...,10200046,2663.09,NaN,Confirmed Payment is Promised,FNWI40013180146,NaN,NaN,NaN,NaN,Transacted
4,FNWI40013208703,Contractual,CO-253 Sequestration,Wheaton,FNWI,40013208703,2.18,0.0,2.18,16015701,...,16015701,292.00,NaN,NaN,FNWI40013208703,NaN,NaN,NaN,NaN,Transacted

In [57]:
Final_df[Final_df['EncounterID_x'] == '220001512862']

Empty DataFrame
Columns: [Unique, Drill TYPE, Project Name, FacilityGroupName, FacilityCode, EncounterID_x, Encounter Insurance Balance, EncounterPatientBalance, EncounterOpenBalance, Current Payer Plan Code, Current Major Payor, Encounter Insurance Balance IM, Group, Primary Payer Plan Code, Secondary Payer Plan Code, PN, Key, Facilitycode_x, EncounterID_y, CurrentFinancialClass U, EncounterInsuranceBalance U, EncounterOpenBalance U, EncounterPatientBalance U, ActivityCode U, CurrentMajoryPayer, CurrentPPC, EncounterTotalCharges U, ActivityCode2, ActivityCode3, Uni_x, Facilitycode_y, EncounterID_y, Current Financial Class, Uni_y, Validation]
Index: []

[0 rows x 35 columns]

In [58]:
Final_df.head()

,Unique,Drill TYPE,Project Name,FacilityGroupName,FacilityCode,EncounterID_x,Encounter Insurance Balance,EncounterPatientBalance,EncounterOpenBalance,Current Payer Plan Code,...,CurrentPPC,EncounterTotalCharges U,ActivityCode2,ActivityCode3,Uni_x,Facilitycode_y,EncounterID_y,Current Financial Class,Uni_y,Validation
0,FNWI40013277560,Contractual,CO-253 Sequestration,Wheaton,FNWI,40013277560,2.19,0.0,2.19,160030011,...,160030011,530.00,NaN,NaN,FNWI40013277560,NaN,NaN,NaN,NaN,Transacted
1,GRMC10009536020,Contractual,CO-253 Sequestration,Flint,GRMC,10009536020,6.92,0.0,6.92,D37,...,D37,1900.00,Applied Contractual/Adjustment,Qualified for TB Drill,GRMC10009536020,NaN,NaN,NaN,NaN,Transacted
2,EKWI31002766923,Contractual,CO-253 Sequestration,Milwaukee,EKWI,31002766923,0.56,0.0,0.56,10100013,...,10100013,275.00,Qualified for TB Drill,Contractual/Adjustment Applied,EKWI31002766923,NaN,NaN,NaN,NaN,Transacted
3,FNWI40013180146,Contractual,CO-253 Sequestration,Wheaton,FNWI,40013180146,33.23,0.0,33.23,10200046,...,10200046,2663.09,NaN,Confirmed Payment is Promised,FNWI40013180146,NaN,NaN,NaN,NaN,Transacted
4,FNWI40013208703,Contractual,CO-253 Sequestration,Wheaton,FNWI,40013208703,2.18,0.0,2.18,16015701,...,16015701,292.00,NaN,NaN,FNWI40013208703,NaN,NaN,NaN,NaN,Transacted

In [59]:
Final_df.shape

(139706, 35)

In [60]:
Final_df['Validation'].value_counts()

Validation
Transacted                  114235
Not Transacted               20578
Validation Mapping Error      4529
Couldn't fetch the data        364
Name: count, dtype: int64

In [61]:
Final_df.groupby('Group')[['Validation']].count()

       Validation
Group
0            4871
1           70696
2           10277
3           18674
4             538
5             132
8             958
9            7561
11           4001
12           1171
13              1
14             15
16           1394
21           4688
22           2211
28           3497
29            229
30           4619
32            104
35           1224
37            571
40           2113
42            161

In [62]:
Final_df.shape

(139706, 35)

In [ ]:
import os
import time
import pandas as pd
from openpyxl import Workbook, load_workbook

start_time = time.time()

file_path = r"C:\Users\IN10052060\OneDrive - R1\Target Balance support\Validation.xlsx"

# Step 1: Check if file exists, delete if yes
if os.path.exists(file_path):
    os.remove(file_path)
    print("🗑️ Existing file deleted.")

# Step 2: Create a fresh Excel file
wb = Workbook()
wb.save(file_path)
print("📂 New Excel file created.")

# Step 3: Export your DataFrame to the new file
with pd.ExcelWriter(file_path, engine='openpyxl', mode='a') as writer:
    Final_df.to_excel(writer, sheet_name='UniqeData', index=False)

end_time = time.time()
elapsed_time = end_time - start_time

print(f"✅ Data successfully written to the sheet in {elapsed_time:.2f} seconds")

🗑️ Existing file deleted.
📂 New Excel file created.

In [ ]:
Final_df.shape