In [1]:
import pandas as pd
import numpy as np
import warnings
import time
warnings.simplefilter("ignore", UserWarning)

## Import Rec vs Work (from Download )

In [2]:

start_time = time.time()

Update_bal = pd.read_excel(
    r"C:\Users\IN10052060\OneDrive - R1\Target Balance support\Balance Output.xlsx",
    sheet_name = 'UniqeData'
)

end_time = time.time()
elapsed_time = end_time - start_time

print(f"File loaded in {elapsed_time:.2f} seconds")

File loaded in 45.39 seconds

In [3]:
Update_bal.shape

(136421, 24)

In [4]:
Update_bal.columns

Index(['Facilitycode', 'EncounterID', 'id', 'CurrentFinancialClass',
       'EncounterInsuranceBalance', 'EncounterOpenBalance',
       'EncounterPatientBalance', 'EncounterTotalCharges',
       'CurrentMajoryPayer', 'CurrentPayorPlanCode', 'CreatedDateTime',
       'ScheduleDateTime', 'Createdby', 'Note', 'UserID', 'Username',
       'ActivityCode', 'act_date_2', 'Username2', 'ActivityCode2',
       'act_date_3', 'Username3', 'ActivityCode3', 'SourceFile'],
      dtype='object')

In [5]:
col = ['Facilitycode', 'EncounterID', 'CurrentFinancialClass', 'EncounterInsuranceBalance',
       'EncounterOpenBalance', 'EncounterPatientBalance', 'ActivityCode' ,'CurrentMajoryPayer', 'CurrentPayorPlanCode']
Update_bal = Update_bal[col]

In [6]:
Update_bal['EncounterID'] = Update_bal['EncounterID'].astype(str).str.lstrip('0')

In [7]:
Update_bal['Uni'] = Update_bal['Facilitycode'].astype(str) + Update_bal['EncounterID'].astype(str)

In [8]:
Update_bal.drop_duplicates(subset = 'Uni', inplace = True)

In [9]:
Update_bal.shape

(136414, 10)

In [10]:
Update_bal.shape

(136414, 10)

In [11]:
Update_bal.head(2)

,Facilitycode,EncounterID,CurrentFinancialClass,EncounterInsuranceBalance,EncounterOpenBalance,EncounterPatientBalance,ActivityCode,CurrentMajoryPayer,CurrentPayorPlanCode,Uni
0,BYFL,87005538233,0000,0.0,213.38,213.38,Transferred Bal to Patient Per Hospital Guidel...,SELF,000000000,BYFL87005538233
1,BYFL,87005560427,4805,0.0,0.00,0.00,Qualified for TB Drill,AUTO/WC,480500001,BYFL87005560427

# Bring the Validation for Last week Dashboard

In [12]:
import pandas as pd
import time

start_time = time.time()

validation = pd.read_excel(
    r"C:\Users\IN10052060\OneDrive - R1\Target Balance support\Validation.xlsx",
    sheet_name = 'UniqeData'
)

end_time = time.time()
elapsed_time = end_time - start_time

print(f"File loaded in {elapsed_time:.2f} seconds")

File loaded in 35.10 seconds

In [13]:
validation.shape

(139745, 35)

In [14]:
validation.head(2)

,Unique,Drill TYPE,Project Name,FacilityGroupName,FacilityCode,EncounterID_x,Encounter Insurance Balance,EncounterPatientBalance,EncounterOpenBalance,Current Payer Plan Code,...,CurrentPPC,EncounterTotalCharges U,ActivityCode2,ActivityCode3,Uni_x,Facilitycode_y,EncounterID_y.1,Current Financial Class,Uni_y,Validation
0,ASWI40013003628,Contractual,36415 + cont +PR,Wheaton,ASWI,40013003628,203.29,0.0,203.29,50073003,...,50073003,297.00,Qualified for TB Drill,System action taken to reset account age,ASWI40013003628,NaN,NaN,NaN,NaN,Not Transacted
1,EMWI40013127560,Contractual,36415 + cont +PR,Wheaton,EMWI,40013127560,7430.79,0.0,6921.75,10312001,...,10312001,8846.18,NaN,NaN,EMWI40013127560,NaN,NaN,NaN,NaN,Transacted

In [15]:
validation.rename({'EncounterID_x' : 'EncounterID'}, axis = 1, inplace  = True)

In [16]:
validation['EncounterID'].isna().sum()

np.int64(0)

In [17]:
validation.head(2)

,Unique,Drill TYPE,Project Name,FacilityGroupName,FacilityCode,EncounterID,Encounter Insurance Balance,EncounterPatientBalance,EncounterOpenBalance,Current Payer Plan Code,...,CurrentPPC,EncounterTotalCharges U,ActivityCode2,ActivityCode3,Uni_x,Facilitycode_y,EncounterID_y.1,Current Financial Class,Uni_y,Validation
0,ASWI40013003628,Contractual,36415 + cont +PR,Wheaton,ASWI,40013003628,203.29,0.0,203.29,50073003,...,50073003,297.00,Qualified for TB Drill,System action taken to reset account age,ASWI40013003628,NaN,NaN,NaN,NaN,Not Transacted
1,EMWI40013127560,Contractual,36415 + cont +PR,Wheaton,EMWI,40013127560,7430.79,0.0,6921.75,10312001,...,10312001,8846.18,NaN,NaN,EMWI40013127560,NaN,NaN,NaN,NaN,Transacted

In [18]:
validation['Key'].isna().sum()

np.int64(0)

In [19]:
validation['EncounterID'] = validation['EncounterID'].astype(str).str.lstrip('0')

In [20]:
validation['PN']= validation['Project Name'].str.strip().str.lower()

In [21]:
validation['Key'] =  validation['FacilityCode'].astype(str) + validation['EncounterID'].astype(str) + validation['PN'].astype(str)

In [22]:
validation = validation[['Key', 'Validation']]
validation.head()

                               Key      Validation
0  ASWI4001300362836415 + cont +pr  Not Transacted
1  EMWI4001312756036415 + cont +pr      Transacted
2    PNTX14624658336415 + cont +pr      Transacted
3  CHWI7900021349236415 + cont +pr      Transacted
4    SVFL90701965736415 + cont +pr      Transacted

In [23]:
import os
import pandas as pd

# Define the folder path
folder_path = r'C:\Users\IN10052060\OneDrive - R1\Target Balance support\Last week'

# Filter for Excel files (.xlsx or .xls)
excel_files = [f for f in os.listdir(folder_path) if f.endswith(('.xlsx', '.xls'))]

# Read and combine all Excel files
dataframes = []
for file in excel_files:
    file_path = os.path.join(folder_path, file)
    df = pd.read_excel(file_path)
    df['source_file'] = file  # Optional: track source
    dataframes.append(df)

# Combine all into one DataFrame
combined_df = pd.concat(dataframes, ignore_index=True)

# Preview
print(combined_df.head())

           Unique   Drill TYPE Project Name FacilityGroupName FacilityCode  \
0  VAIN13419656-1  Contractual      CA file      Indianapolis         VAIN
1  MTTN7527999485  Contractual      CA file         Nashville         MTTN
2  DCTX8089079862  Contractual      CA file            Austin         DCTX
3   EDTX158117797  Contractual      CA file            Austin         EDTX
4  THTN8102140835  Contractual      CA file         Nashville         THTN

  EncounterID TB Control  Encounter Insurance Balance  \
0  13419656-1    CA file                      8084.50
1  7527999485    CA file                      7761.84
2  8089079862    CA file                      7702.40
3   158117797    CA file                      7457.15
4  8102140835    CA file                      7256.88

   EncounterPatientBalance  EncounterOpenBalance  ...  DFD.1 Key   DC  \
0                      0.0               8084.50  ...    NaN NaN  NaN
1                      0.0               7761.84  ...    NaN NaN  NaN
2                      0.0               7702.40  ...    NaN NaN  NaN
3                      0.0               7457.15  ...    NaN NaN  NaN
4                      0.0               7256.88  ...    NaN NaN  NaN

                     Date2  Secondary Patient Responsibility  \
0  Wednesday, May 27, 2026                               NaN
1  Wednesday, May 27, 2026                               NaN
2  Wednesday, May 27, 2026                               NaN
3  Wednesday, May 27, 2026                               NaN
4  Wednesday, May 27, 2026                               NaN

  Current Payer Plan Name Tertiary Payer Plan Name Assigned Y/N Group  \
0                     NaN                      NaN          NaN     1
1                     NaN                      NaN          NaN     1
2                     NaN                      NaN          NaN     1
3                     NaN                      NaN          NaN     1
4                     NaN                      NaN          NaN     1

       source_file
0  RW WE 0529.xlsx
1  RW WE 0529.xlsx
2  RW WE 0529.xlsx
3  RW WE 0529.xlsx
4  RW WE 0529.xlsx

[5 rows x 130 columns]

In [24]:
combined_df.columns

Index(['Unique', 'Drill TYPE', 'Project Name', 'FacilityGroupName',
       'FacilityCode', 'EncounterID', 'TB Control',
       'Encounter Insurance Balance', 'EncounterPatientBalance',
       'EncounterOpenBalance',
       ...
       'DFD.1', 'Key', 'DC', 'Date2', 'Secondary Patient Responsibility',
       'Current Payer Plan Name', 'Tertiary Payer Plan Name', 'Assigned Y/N',
       'Group', 'source_file'],
      dtype='object', length=130)

In [25]:
combined_df.shape

(139745, 130)

In [26]:
df = combined_df.copy()

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 139745 entries, 0 to 139744
Columns: 130 entries, Unique to source_file
dtypes: bool(1), datetime64[ns](3), float64(36), int64(2), object(88)
memory usage: 137.7+ MB

In [28]:
df.shape

(139745, 130)

In [29]:
validation.shape[0] - df.shape[0]

0

In [30]:
FM =pd.read_excel(r"C:\Users\IN10052060\Downloads\Facility mapping.xlsx", sheet_name = 'facility mapping')

In [31]:
FM.columns

Index(['TB Facility Code', 'Entity', '7A and 7B',
       'Ascension KPI Clusters - Crowe', 'Ministry', 'Scorecard Cluster',
       'Site', 'Asc/Non Asc', 'Epic/Non-EPIC', 'Recd/work', 'Entity Group',
       'BOT Site', 'Capacity', 'Creds', 'Weekly BOT Prod', 'ADR', 'New',
       'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19'],
      dtype='object')

In [32]:
FM = FM[['TB Facility Code', 'Entity Group', 'Entity']]

In [33]:
FM.drop_duplicates(subset = ['TB Facility Code'], inplace = True)

In [34]:
FM.shape

(420, 3)

In [35]:
df = df.merge(FM, left_on = 'FacilityCode', right_on = 'TB Facility Code', how = 'left')

In [36]:
df['EncounterID'] = df['EncounterID'].astype(str).str.lstrip('0')

In [37]:
df = df.copy()
df['Unique'] = df['FacilityCode'].astype(str) + df['EncounterID'].astype(str)

In [38]:
df.head(2)

,Unique,Drill TYPE,Project Name,FacilityGroupName,FacilityCode,EncounterID,TB Control,Encounter Insurance Balance,EncounterPatientBalance,EncounterOpenBalance,...,Date2,Secondary Patient Responsibility,Current Payer Plan Name,Tertiary Payer Plan Name,Assigned Y/N,Group,source_file,TB Facility Code,Entity Group_y,Entity_y
0,VAIN13419656-1,Contractual,CA file,Indianapolis,VAIN,13419656-1,CA file,8084.50,0.0,8084.50,...,"Wednesday, May 27, 2026",NaN,NaN,NaN,NaN,1,RW WE 0529.xlsx,VAIN,Ascension,Indianapolis
1,MTTN7527999485,Contractual,CA file,Nashville,MTTN,7527999485,CA file,7761.84,0.0,7761.84,...,"Wednesday, May 27, 2026",NaN,NaN,NaN,NaN,1,RW WE 0529.xlsx,MTTN,Ascension,Nashville

In [39]:
Update_bal.head()

,Facilitycode,EncounterID,CurrentFinancialClass,EncounterInsuranceBalance,EncounterOpenBalance,EncounterPatientBalance,ActivityCode,CurrentMajoryPayer,CurrentPayorPlanCode,Uni
0,BYFL,87005538233,0000,0.00,213.38,213.38,Transferred Bal to Patient Per Hospital Guidel...,SELF,000000000,BYFL87005538233
1,BYFL,87005560427,4805,0.00,0.00,0.00,Qualified for TB Drill,AUTO/WC,480500001,BYFL87005560427
2,BYFL,87005563199,0861,55.59,55.59,0.00,Qualified for TB Drill,BLUE CROSS,086100000,BYFL87005563199
3,BYFL,87005566408,0000,0.00,916.04,916.04,Transferred Bal to Patient Per Hospital Guidel...,SELF,000000000,BYFL87005566408
4,BYFL,87005578635,0000,0.00,277.94,277.94,Transferred Bal to Patient Per Hospital Guidel...,SELF,000000000,BYFL87005578635

In [40]:
update_Insurance_bal = Update_bal[['Uni', 'EncounterInsuranceBalance']]

In [41]:
update_Insurance_bal.head()

               Uni  EncounterInsuranceBalance
0  BYFL87005538233                       0.00
1  BYFL87005560427                       0.00
2  BYFL87005563199                      55.59
3  BYFL87005566408                       0.00
4  BYFL87005578635                       0.00

In [42]:
df.shape

(139745, 133)

In [43]:
df = df.merge(update_Insurance_bal, how = 'left', left_on = 'Unique', right_on = 'Uni')
df.head()

,Unique,Drill TYPE,Project Name,FacilityGroupName,FacilityCode,EncounterID,TB Control,Encounter Insurance Balance,EncounterPatientBalance,EncounterOpenBalance,...,Current Payer Plan Name,Tertiary Payer Plan Name,Assigned Y/N,Group,source_file,TB Facility Code,Entity Group_y,Entity_y,Uni,EncounterInsuranceBalance
0,VAIN13419656-1,Contractual,CA file,Indianapolis,VAIN,13419656-1,CA file,8084.50,0.0,8084.50,...,NaN,NaN,NaN,1,RW WE 0529.xlsx,VAIN,Ascension,Indianapolis,VAIN13419656-1,0.0
1,MTTN7527999485,Contractual,CA file,Nashville,MTTN,7527999485,CA file,7761.84,0.0,7761.84,...,NaN,NaN,NaN,1,RW WE 0529.xlsx,MTTN,Ascension,Nashville,MTTN7527999485,0.0
2,DCTX8089079862,Contractual,CA file,Austin,DCTX,8089079862,CA file,7702.40,0.0,7702.40,...,NaN,NaN,NaN,1,RW WE 0529.xlsx,DCTX,Ascension,Austin,DCTX8089079862,0.0
3,EDTX158117797,Contractual,CA file,Austin,EDTX,158117797,CA file,7457.15,0.0,7457.15,...,NaN,NaN,NaN,1,RW WE 0529.xlsx,EDTX,Ascension,Austin,EDTX158117797,0.0
4,THTN8102140835,Contractual,CA file,Nashville,THTN,8102140835,CA file,7256.88,0.0,7256.88,...,NaN,NaN,NaN,1,RW WE 0529.xlsx,THTN,Ascension,Nashville,THTN8102140835,0.0

In [44]:
df['Sum of Encounter Insurance Balance_4'] = df['EncounterInsuranceBalance']

In [45]:
df = df.copy()
df['Insurance balance diff'] = (df['Encounter Insurance Balance'] - df['Sum of Encounter Insurance Balance_4'])

In [46]:
df['Insurance balance diff'].min()

np.float64(-4912335.8)

In [47]:
df['New CF$'].min()

np.float64(-84372.0)

In [48]:
df[df['Unique'] == 'SVFL822450714']['New CF$']

Series([], Name: New CF$, dtype: float64)

In [49]:
df['PN']= df['Project Name'].str.strip().str.lower()

In [50]:
df['SuperUnique'] =  df['FacilityCode'].astype(str) + df['EncounterID'].astype(str) + df['PN'].astype(str)

In [51]:
df.drop_duplicates(subset = ['SuperUnique'], inplace = True)

In [52]:
df.shape

(139463, 138)

In [53]:
validation['Validation'].unique()

array(['Not Transacted', 'Transacted', "Couldn't fetch the data"],
      dtype=object)

In [54]:
validation = validation.copy()
validation.drop_duplicates(subset = ['Key'], inplace = True)

In [55]:
validation.shape

(139463, 2)

In [56]:
validation.head(2)

                               Key      Validation
0  ASWI4001300362836415 + cont +pr  Not Transacted
1  EMWI4001312756036415 + cont +pr      Transacted

In [57]:
df.head()

,Unique,Drill TYPE,Project Name,FacilityGroupName,FacilityCode,EncounterID,TB Control,Encounter Insurance Balance,EncounterPatientBalance,EncounterOpenBalance,...,Group,source_file,TB Facility Code,Entity Group_y,Entity_y,Uni,EncounterInsuranceBalance,Sum of Encounter Insurance Balance_4,Insurance balance diff,PN
0,VAIN13419656-1,Contractual,CA file,Indianapolis,VAIN,13419656-1,CA file,8084.50,0.0,8084.50,...,1,RW WE 0529.xlsx,VAIN,Ascension,Indianapolis,VAIN13419656-1,0.0,0.0,8084.50,ca file
1,MTTN7527999485,Contractual,CA file,Nashville,MTTN,7527999485,CA file,7761.84,0.0,7761.84,...,1,RW WE 0529.xlsx,MTTN,Ascension,Nashville,MTTN7527999485,0.0,0.0,7761.84,ca file
2,DCTX8089079862,Contractual,CA file,Austin,DCTX,8089079862,CA file,7702.40,0.0,7702.40,...,1,RW WE 0529.xlsx,DCTX,Ascension,Austin,DCTX8089079862,0.0,0.0,7702.40,ca file
3,EDTX158117797,Contractual,CA file,Austin,EDTX,158117797,CA file,7457.15,0.0,7457.15,...,1,RW WE 0529.xlsx,EDTX,Ascension,Austin,EDTX158117797,0.0,0.0,7457.15,ca file
4,THTN8102140835,Contractual,CA file,Nashville,THTN,8102140835,CA file,7256.88,0.0,7256.88,...,1,RW WE 0529.xlsx,THTN,Ascension,Nashville,THTN8102140835,0.0,0.0,7256.88,ca file

In [58]:
df.shape

(139463, 138)

In [59]:
# Last Week for Dashboard
LWFD = df.merge(validation, how = 'left',left_on = 'SuperUnique', right_on = 'Key')
LWFD.shape

(139463, 140)

In [60]:
LWFD[LWFD['Validation'].isna()]

,Unique,Drill TYPE,Project Name,FacilityGroupName,FacilityCode,EncounterID,TB Control,Encounter Insurance Balance,EncounterPatientBalance,EncounterOpenBalance,...,TB Facility Code,Entity Group_y,Entity_y,Uni,EncounterInsuranceBalance,Sum of Encounter Insurance Balance_4,Insurance balance diff,PN,Key_y,Validation
102477,ABCD123456789,Contractual,CPT -93010 Denial,NaN,ABCD,123456789,CPT -93010 Denial,NaN,NaN,NaN,...,ABCD,No Volume,No Volume,NaN,NaN,NaN,NaN,cpt -93010 denial,NaN,NaN
102481,ABCD123456789,Contractual,HCPC A4627 Adjustment,NaN,ABCD,123456789,HCPC A4627 Adjustment,NaN,NaN,NaN,...,ABCD,No Volume,No Volume,NaN,NaN,NaN,NaN,hcpc a4627 adjustment,NaN,NaN
102603,ABCD123456789,Contractual,Pennstate C code,NaN,ABCD,123456789,Pennstate C code,NaN,NaN,NaN,...,ABCD,No Volume,No Volume,NaN,NaN,NaN,NaN,pennstate c code,NaN,NaN
102610,ABCD123456789,Contractual,Sutter Prop 56,NaN,ABCD,123456789,Sutter Prop 56,NaN,NaN,NaN,...,ABCD,No Volume,No Volume,NaN,NaN,NaN,NaN,sutter prop 56,NaN,NaN

In [61]:
LWFD.columns

Index(['Unique', 'Drill TYPE', 'Project Name', 'FacilityGroupName',
       'FacilityCode', 'EncounterID', 'TB Control',
       'Encounter Insurance Balance', 'EncounterPatientBalance',
       'EncounterOpenBalance',
       ...
       'TB Facility Code', 'Entity Group_y', 'Entity_y', 'Uni',
       'EncounterInsuranceBalance', 'Sum of Encounter Insurance Balance_4',
       'Insurance balance diff', 'PN', 'Key_y', 'Validation'],
      dtype='object', length=140)

In [62]:
df.columns

Index(['Unique', 'Drill TYPE', 'Project Name', 'FacilityGroupName',
       'FacilityCode', 'EncounterID', 'TB Control',
       'Encounter Insurance Balance', 'EncounterPatientBalance',
       'EncounterOpenBalance',
       ...
       'Group', 'source_file', 'TB Facility Code', 'Entity Group_y',
       'Entity_y', 'Uni', 'EncounterInsuranceBalance',
       'Sum of Encounter Insurance Balance_4', 'Insurance balance diff', 'PN'],
      dtype='object', length=138)

In [63]:
LWFD['Validation'].unique()

array(['Transacted', "Couldn't fetch the data", 'Not Transacted', nan],
      dtype=object)

In [64]:
df_Server_Issue = LWFD[LWFD['Validation'] == "Couldn't fetch the data"]

In [65]:
df_Validation_Req = LWFD[LWFD['Validation'] == "Validation Mapping Error"]

In [66]:
df_NT = LWFD[LWFD['Validation'] == "Not Transacted"]

In [67]:
df_T = LWFD[LWFD['Validation'] =="Transacted"]

In [68]:
df['Final Transaction']

0         Transacted
1         Transacted
2         Transacted
3         Transacted
4         Transacted
             ...
139740    Transacted
139741    Transacted
139742    Transacted
139743    Transacted
139744    Transacted
Name: Final Transaction, Length: 139463, dtype: object

In [69]:
LWFD.shape

(139463, 140)

In [70]:
df_Server_Issue.shape

(264, 140)

In [71]:
df_Validation_Req.shape

(0, 140)

In [72]:
df_NT.shape

(17748, 140)

In [73]:
df_T.shape

(121447, 140)

In [74]:
LWFD['Validation']

0             Transacted
1             Transacted
2             Transacted
3             Transacted
4             Transacted
               ...
139458        Transacted
139459        Transacted
139460    Not Transacted
139461        Transacted
139462    Not Transacted
Name: Validation, Length: 139463, dtype: object

In [75]:
LWFD['Validation'].value_counts(dropna=False)

Validation
Transacted                 121447
Not Transacted              17748
Couldn't fetch the data       264
NaN                             4
Name: count, dtype: int64

In [76]:
df_Server_Issue['Validation'].unique()

array(["Couldn't fetch the data"], dtype=object)

In [77]:
df_Server_Issue.columns

Index(['Unique', 'Drill TYPE', 'Project Name', 'FacilityGroupName',
       'FacilityCode', 'EncounterID', 'TB Control',
       'Encounter Insurance Balance', 'EncounterPatientBalance',
       'EncounterOpenBalance',
       ...
       'TB Facility Code', 'Entity Group_y', 'Entity_y', 'Uni',
       'EncounterInsuranceBalance', 'Sum of Encounter Insurance Balance_4',
       'Insurance balance diff', 'PN', 'Key_y', 'Validation'],
      dtype='object', length=140)

In [78]:

df_Server_Issue['Status1'].unique()

array(['Transacted by TB', 'Worked not Transacted',
       'Transacted by Others', 'Pending to assign', 'Pending with TB'],
      dtype=object)

In [79]:
df_Server_Issue['Completion status'].unique()

array(['Completed', 'Pending to assign', 'Pending with TB'], dtype=object)

In [80]:
df_Server_Issue['Tranasction status'].unique()

array(['Transacted by TB', 'Worked not transacted',
       'Transacted by System', 'Not worked not transacted'], dtype=object)

In [81]:
df_Server_Issue = df_Server_Issue.copy()
df_Server_Issue['Validation'] = df_Server_Issue['Final Transaction']

In [82]:
df_Server_Issue['Validation'].unique()

array(['Transacted', 'Not Transacted'], dtype=object)

In [83]:
df_Server_Issue_T = df_Server_Issue[df_Server_Issue['Validation'] == 'Transacted']

In [84]:
df_Server_Issue_NT = df_Server_Issue[df_Server_Issue['Validation'] == 'Not Transacted']

In [85]:
df_Server_Issue['Validation'].unique()

array(['Transacted', 'Not Transacted'], dtype=object)

In [86]:
df_Validation_Req['Validation'].unique()

array([], dtype=object)

In [87]:
df_Validation_Req = df_Validation_Req.copy()
df_Validation_Req['Validation'] = df_Validation_Req['Final Transaction']

In [88]:
df_Validation_Req['Validation'].unique()

array([], dtype=object)

In [89]:
df_Validation_Req_T = df_Validation_Req[df_Validation_Req['Validation'] == 'Transacted']

In [90]:
df_Validation_Req_NT = df_Validation_Req[df_Validation_Req['Validation'] == 'Not Transacted']

In [91]:
df_NT = pd.concat([df_NT,df_Server_Issue_NT,df_Validation_Req_NT], axis = 0)

In [92]:
df_NT.shape

(17829, 140)

In [93]:
df_T = pd.concat([df_T, df_Server_Issue_T, df_Validation_Req_T], axis = 0)

In [94]:
df_T.shape

(121630, 140)

In [95]:
df_NT['Status1'].unique()

array(['Transacted by Others', 'Worked not Transacted',
       'Transacted by TB', 'Transacted by BOT', 'Pending with TB',
       'Pending to assign', 'Pending with BOT', 'Pending with Ops'],
      dtype=object)

In [96]:
def status(row):
    Status = row['Status1']
    
    mapping = {
        "Transacted by Others": "Pending with Ops",
        "Transacted by TB": "Pending with TB",
        "Transacted by BOT": "Pending with BOT"
    }
    
    if Status in mapping:
        return mapping[Status]
    else :
        return Status

In [97]:
df_NT = df_NT.copy()
df_NT['Status1'] = df_NT.apply(status, axis = 1)

In [98]:
df_NT['Status1'].unique()

array(['Pending with Ops', 'Worked not Transacted', 'Pending with TB',
       'Pending with BOT', 'Pending to assign'], dtype=object)

In [99]:
df_NT['Completion status'].unique()

array(['Completed', 'Pending with TB', 'Pending to assign',
       'Pending with BOT', 'Pending with Ops'], dtype=object)

In [100]:
def completion_status(row):
    Status = row['Status1']
    CS = row['Completion status']

    
    if CS == "Completed":
        return Status
    else:
        return CS

In [101]:
df_NT = df_NT.copy()
df_NT['Completion status'] = df_NT.apply(completion_status, axis = 1)

In [102]:
df_NT['Completion status'].unique()

array(['Pending with Ops', 'Worked not Transacted', 'Pending with TB',
       'Pending with BOT', 'Pending to assign'], dtype=object)

In [103]:
df_NT['Tranasction status'].unique()

array(['Transacted by System', 'Worked not transacted',
       'Transacted by TB', 'Transacted by User', 'Transacted by BOT',
       'Not worked not transacted'], dtype=object)

In [104]:
def Transaction_Status(row):
    CS = row['Completion status']
    if CS == 'Worked not Transacted':
        return 'Worked not Transacted'
    else:
        return 'Not worked not transacted'

In [105]:
df_NT = df_NT.copy()
df_NT['Tranasction status'] = df_NT.apply(Transaction_Status, axis = 1)

In [106]:
df_NT['Tranasction status'].unique()

array(['Not worked not transacted', 'Worked not Transacted'], dtype=object)

In [107]:
df_T.shape

(121630, 140)

In [108]:
df_T['Status1'].unique()

array(['Transacted by BOT', 'Transacted by Others', 'Transacted by TB',
       'Worked not Transacted', 'Pending to assign', 'Pending with TB',
       'Pending with BOT'], dtype=object)

In [109]:
def t_status(row):
    Status = row['Status1']
    
    mapping = {
        "Pending with TB": "Transacted by TB",
        "Pending to assign": "Transacted by TB",
        "Pending with Ops": "Transacted by TB",
        "Pending with BOT" : "Transacted by BOT",
        "Worked not Transacted" : "Transacted by TB"
    }
    
    if Status in mapping:
        return mapping[Status]
    else :
        return Status

In [110]:
df_T = df_T.copy()
df_T['Status1'] = df_T.apply(t_status, axis = 1)

In [111]:
df_T['Status1'].unique()

array(['Transacted by BOT', 'Transacted by Others', 'Transacted by TB'],
      dtype=object)

In [112]:
df_T['Completion status'].unique()

array(['Completed', 'Pending to assign', 'Pending with TB',
       'Pending with BOT'], dtype=object)

In [113]:
df_T['Completion status'] = "Completed"

In [114]:
df_T['Completion status'].unique()

array(['Completed'], dtype=object)

In [115]:
df_T['Tranasction status'].unique()

array(['Transacted by BOT', 'Transacted by User', 'Transacted by TB',
       'Transacted by System', 'Worked not transacted',
       'Not worked not transacted'], dtype=object)

In [116]:
def T_Transaction_Status(row):
    TS = row['Tranasction status']
    if TS == 'Not worked not transacted':
        return 'Transacted by TB'
    elif TS == "Worked not transacted":
        return "Transacted by TB"

    else:
        return TS

In [117]:
df_T = df_T.copy()
df_T['Tranasction status'] = df_T.apply(T_Transaction_Status, axis = 1)

In [118]:
df_T['Tranasction status'].unique()

array(['Transacted by BOT', 'Transacted by User', 'Transacted by TB',
       'Transacted by System'], dtype=object)

In [119]:
df_total = df_T.shape[0] + df_NT.shape[0]
df_total

139459

In [120]:
df_T.shape

(121630, 140)

In [121]:
df_NT.shape

(17829, 140)

In [122]:
LWFD.shape[0]

139463

In [123]:
df_total

139459

In [124]:
if LWFD.shape[0] == df_total:
    print("Data is accurately Match")

In [125]:
final_Lw_data = pd.concat([df_NT,df_T], axis = 0)

In [126]:
final_Lw_data.shape

(139459, 140)

In [127]:
final_Lw_data['New CF$'].min()

np.float64(-84372.0)

In [128]:
final_Lw_data.shape

(139459, 140)

In [129]:
final_Lw_data.head(2)

,Unique,Drill TYPE,Project Name,FacilityGroupName,FacilityCode,EncounterID,TB Control,Encounter Insurance Balance,EncounterPatientBalance,EncounterOpenBalance,...,TB Facility Code,Entity Group_y,Entity_y,Uni,EncounterInsuranceBalance,Sum of Encounter Insurance Balance_4,Insurance balance diff,PN,Key_y,Validation
60879,P152271500212924,Contractual,36415 + cont +PR,Providence,P152,271500212924,36415 + cont +PR,0.0,8.91,8.91,...,P152,Providence,Providence,P152271500212924,0.0,0.0,0.0,36415 + cont +pr,P15227150021292436415 + cont +pr,Not Transacted
60880,P152271500215769,Contractual,36415 + cont +PR,Providence,P152,271500215769,36415 + cont +PR,0.0,12.14,12.14,...,P152,Providence,Providence,P152271500215769,0.0,0.0,0.0,36415 + cont +pr,P15227150021576936415 + cont +pr,Not Transacted

In [130]:
final_Lw_data.columns

Index(['Unique', 'Drill TYPE', 'Project Name', 'FacilityGroupName',
       'FacilityCode', 'EncounterID', 'TB Control',
       'Encounter Insurance Balance', 'EncounterPatientBalance',
       'EncounterOpenBalance',
       ...
       'TB Facility Code', 'Entity Group_y', 'Entity_y', 'Uni',
       'EncounterInsuranceBalance', 'Sum of Encounter Insurance Balance_4',
       'Insurance balance diff', 'PN', 'Key_y', 'Validation'],
      dtype='object', length=140)

In [131]:
final_Lw_data.shape

(139459, 140)

In [132]:
final_Lw_data['Final Transaction'] = final_Lw_data['Validation']

In [133]:
final_Lw_data['Final Transaction'].value_counts()

Final Transaction
Transacted        121630
Not Transacted     17829
Name: count, dtype: int64

In [134]:
final_Lw_data['Validation'].value_counts()

Validation
Transacted        121630
Not Transacted     17829
Name: count, dtype: int64

In [135]:
final_Lw_data.drop('Validation', axis = 1, inplace = True)

In [136]:
final_Lw_data.columns

Index(['Unique', 'Drill TYPE', 'Project Name', 'FacilityGroupName',
       'FacilityCode', 'EncounterID', 'TB Control',
       'Encounter Insurance Balance', 'EncounterPatientBalance',
       'EncounterOpenBalance',
       ...
       'source_file', 'TB Facility Code', 'Entity Group_y', 'Entity_y', 'Uni',
       'EncounterInsuranceBalance', 'Sum of Encounter Insurance Balance_4',
       'Insurance balance diff', 'PN', 'Key_y'],
      dtype='object', length=139)

In [137]:
final_Lw_data.rename({'Entity Group_y':'Entity Group', 'Entity_y':'Entity'}, axis = 1, inplace = True)

In [138]:
final_Lw_data.drop(['Entity Group_x', 'Entity_x'], axis = 1, inplace = True)

In [139]:
final_Lw_data.shape

(139459, 137)

In [140]:
final_Lw_data.head()

,Unique,Drill TYPE,Project Name,FacilityGroupName,FacilityCode,EncounterID,TB Control,Encounter Insurance Balance,EncounterPatientBalance,EncounterOpenBalance,...,source_file,TB Facility Code,Entity Group,Entity,Uni,EncounterInsuranceBalance,Sum of Encounter Insurance Balance_4,Insurance balance diff,PN,Key_y
60879,P152271500212924,Contractual,36415 + cont +PR,Providence,P152,271500212924,36415 + cont +PR,0.0,8.91,8.91,...,RW WE 0529.xlsx,P152,Providence,Providence,P152271500212924,0.0,0.0,0.0,36415 + cont +pr,P15227150021292436415 + cont +pr
60880,P152271500215769,Contractual,36415 + cont +PR,Providence,P152,271500215769,36415 + cont +PR,0.0,12.14,12.14,...,RW WE 0529.xlsx,P152,Providence,Providence,P152271500215769,0.0,0.0,0.0,36415 + cont +pr,P15227150021576936415 + cont +pr
60881,P163320501282112,Contractual,36415 + cont +PR,Providence,P163,320501282112,36415 + cont +PR,0.0,259.70,259.70,...,RW WE 0529.xlsx,P163,Providence,Providence,P163320501282112,0.0,0.0,0.0,36415 + cont +pr,P16332050128211236415 + cont +pr
60882,P161691300317149,Contractual,36415 + cont +PR,Providence,P161,691300317149,36415 + cont +PR,0.0,418.31,418.31,...,RW WE 0529.xlsx,P161,Providence,Providence,P161691300317149,0.0,0.0,0.0,36415 + cont +pr,P16169130031714936415 + cont +pr
60883,P161691300346602,Contractual,36415 + cont +PR,Providence,P161,691300346602,36415 + cont +PR,0.0,300.00,300.00,...,RW WE 0529.xlsx,P161,Providence,Providence,P161691300346602,0.0,0.0,0.0,36415 + cont +pr,P16169130034660236415 + cont +pr

In [141]:
final_Lw_data['Entity'].value_counts(dropna = False)

Entity
Lifepoint                              19444
Indianapolis                           14989
Providence                             10833
Austin                                 10671
Nashville                               9526
Henry Ford                              9520
IH                                      8418
Pensacola                               6859
Quorum                                  6836
Tulsa                                   6256
Jacksonville                            5617
Sutter Health                           5265
Wheaton                                 4495
Wichita                                 4172
Waco                                    3427
Pennstate                               3291
Milwaukee                               2350
Alexian                                 1751
WI-Ministry                             1698
Baltimore                               1214
Swedish                                 1053
Beacon                                  1023
Presence                                 483
Mercy Heatlh                             132
No Volume                                 57
Prime Healthcare                          52
University of Alabama at Birmingham       21
NaN                                        6
Name: count, dtype: int64

In [142]:
FM.columns

Index(['TB Facility Code', 'Entity Group', 'Entity'], dtype='object')

In [143]:
final_Lw_data.head()

,Unique,Drill TYPE,Project Name,FacilityGroupName,FacilityCode,EncounterID,TB Control,Encounter Insurance Balance,EncounterPatientBalance,EncounterOpenBalance,...,source_file,TB Facility Code,Entity Group,Entity,Uni,EncounterInsuranceBalance,Sum of Encounter Insurance Balance_4,Insurance balance diff,PN,Key_y
60879,P152271500212924,Contractual,36415 + cont +PR,Providence,P152,271500212924,36415 + cont +PR,0.0,8.91,8.91,...,RW WE 0529.xlsx,P152,Providence,Providence,P152271500212924,0.0,0.0,0.0,36415 + cont +pr,P15227150021292436415 + cont +pr
60880,P152271500215769,Contractual,36415 + cont +PR,Providence,P152,271500215769,36415 + cont +PR,0.0,12.14,12.14,...,RW WE 0529.xlsx,P152,Providence,Providence,P152271500215769,0.0,0.0,0.0,36415 + cont +pr,P15227150021576936415 + cont +pr
60881,P163320501282112,Contractual,36415 + cont +PR,Providence,P163,320501282112,36415 + cont +PR,0.0,259.70,259.70,...,RW WE 0529.xlsx,P163,Providence,Providence,P163320501282112,0.0,0.0,0.0,36415 + cont +pr,P16332050128211236415 + cont +pr
60882,P161691300317149,Contractual,36415 + cont +PR,Providence,P161,691300317149,36415 + cont +PR,0.0,418.31,418.31,...,RW WE 0529.xlsx,P161,Providence,Providence,P161691300317149,0.0,0.0,0.0,36415 + cont +pr,P16169130031714936415 + cont +pr
60883,P161691300346602,Contractual,36415 + cont +PR,Providence,P161,691300346602,36415 + cont +PR,0.0,300.00,300.00,...,RW WE 0529.xlsx,P161,Providence,Providence,P161691300346602,0.0,0.0,0.0,36415 + cont +pr,P16169130034660236415 + cont +pr

# Accounts Delete (EI and FC)

In [144]:
file = pd.read_excel(r'C:\Users\IN10052060\Desktop\Account delete\file 1 (EI and FC).xlsx')

In [145]:
file.head()

  FacilityCode EncounterID
0         HMPA  2016516426
1         HMPA  2013116783
2         HMPA  2015516249
3         HMPA  2016232063
4         HMPA  2011828953

In [146]:
file['EncounterID'] = file['EncounterID'].astype(str).str.lstrip('0')
file = file.copy()
file['Key_EI_FC'] = file['FacilityCode'].astype(str) + file['EncounterID'].astype(str)

In [147]:
file = file[['Key_EI_FC']]

In [148]:
file.drop_duplicates(subset = 'Key_EI_FC', inplace = True)

In [149]:
df_merge_file = final_Lw_data.copy()

In [150]:
df_merge_file.shape

(139459, 137)

In [151]:
df_merge_file = df_merge_file.merge(file, left_on = 'Unique', right_on = 'Key_EI_FC', how = 'left')

In [152]:
df_merge_file.head()

,Unique,Drill TYPE,Project Name,FacilityGroupName,FacilityCode,EncounterID,TB Control,Encounter Insurance Balance,EncounterPatientBalance,EncounterOpenBalance,...,TB Facility Code,Entity Group,Entity,Uni,EncounterInsuranceBalance,Sum of Encounter Insurance Balance_4,Insurance balance diff,PN,Key_y,Key_EI_FC
0,P152271500212924,Contractual,36415 + cont +PR,Providence,P152,271500212924,36415 + cont +PR,0.0,8.91,8.91,...,P152,Providence,Providence,P152271500212924,0.0,0.0,0.0,36415 + cont +pr,P15227150021292436415 + cont +pr,NaN
1,P152271500215769,Contractual,36415 + cont +PR,Providence,P152,271500215769,36415 + cont +PR,0.0,12.14,12.14,...,P152,Providence,Providence,P152271500215769,0.0,0.0,0.0,36415 + cont +pr,P15227150021576936415 + cont +pr,NaN
2,P163320501282112,Contractual,36415 + cont +PR,Providence,P163,320501282112,36415 + cont +PR,0.0,259.70,259.70,...,P163,Providence,Providence,P163320501282112,0.0,0.0,0.0,36415 + cont +pr,P16332050128211236415 + cont +pr,NaN
3,P161691300317149,Contractual,36415 + cont +PR,Providence,P161,691300317149,36415 + cont +PR,0.0,418.31,418.31,...,P161,Providence,Providence,P161691300317149,0.0,0.0,0.0,36415 + cont +pr,P16169130031714936415 + cont +pr,NaN
4,P161691300346602,Contractual,36415 + cont +PR,Providence,P161,691300346602,36415 + cont +PR,0.0,300.00,300.00,...,P161,Providence,Providence,P161691300346602,0.0,0.0,0.0,36415 + cont +pr,P16169130034660236415 + cont +pr,NaN

In [153]:
df_merge_file[df_merge_file['Key_EI_FC'].isna()].shape

(137950, 138)

In [154]:
df_merge_file[df_merge_file['Key_EI_FC'].notna()].shape # Matching Records

(1509, 138)

In [155]:
df_merge_file.shape

(139459, 138)

In [156]:
df_merge_file = df_merge_file[df_merge_file['Key_EI_FC'].isna()]

In [157]:
df_merge_file.shape

(137950, 138)

# Status Change Epic

In [158]:
file_2 = pd.read_excel(r'C:\Users\IN10052060\Desktop\Status Change Epic\Status Change (Epic).xlsx', sheet_name = 'Sheet1')

In [159]:
file_2.head()

  FacilityCode  EncounterID
0         E138  24000015989
1         E154  18000116887
2         E138  24000016386
3         E128  19000009820
4         E132  21500158090

In [160]:
file_2['EncounterID'] = file_2['EncounterID'].astype(str).str.lstrip('0')
file_2 = file_2.copy()
file_2['Key_SC_Epic_EI_FC'] = file_2['FacilityCode'].astype(str) + file_2['EncounterID'].astype(str)

In [161]:
file_2

    FacilityCode   EncounterID Key_SC_Epic_EI_FC
0           E138   24000015989   E13824000015989
1           E154   18000116887   E15418000116887
2           E138   24000016386   E13824000016386
3           E128   19000009820   E12819000009820
4           E132   21500158090   E13221500158090
..           ...           ...               ...
895         P178  361700692226  P178361700692226
896         P118  316004865009  P118316004865009
897         P119  330003194854  P119330003194854
898         P157  772000778880  P157772000778880
899         P151  270000696737  P151270000696737

[900 rows x 3 columns]

In [162]:
file_2.drop_duplicates(subset = 'Key_SC_Epic_EI_FC', inplace = True)

In [163]:
file_2 = file_2[['Key_SC_Epic_EI_FC']]

In [164]:
df_SC_Epic_EI_FC = df_merge_file.copy()

In [165]:
df_SC_Epic_EI_FC.shape

(137950, 138)

In [166]:
df_SC_Epic_EI_FC = df_SC_Epic_EI_FC.merge(file_2, how = 'left', left_on = 'Unique', right_on = 'Key_SC_Epic_EI_FC')

In [167]:
df_SC_Epic_EI_FC.head()

,Unique,Drill TYPE,Project Name,FacilityGroupName,FacilityCode,EncounterID,TB Control,Encounter Insurance Balance,EncounterPatientBalance,EncounterOpenBalance,...,Entity Group,Entity,Uni,EncounterInsuranceBalance,Sum of Encounter Insurance Balance_4,Insurance balance diff,PN,Key_y,Key_EI_FC,Key_SC_Epic_EI_FC
0,P152271500212924,Contractual,36415 + cont +PR,Providence,P152,271500212924,36415 + cont +PR,0.0,8.91,8.91,...,Providence,Providence,P152271500212924,0.0,0.0,0.0,36415 + cont +pr,P15227150021292436415 + cont +pr,NaN,NaN
1,P152271500215769,Contractual,36415 + cont +PR,Providence,P152,271500215769,36415 + cont +PR,0.0,12.14,12.14,...,Providence,Providence,P152271500215769,0.0,0.0,0.0,36415 + cont +pr,P15227150021576936415 + cont +pr,NaN,NaN
2,P163320501282112,Contractual,36415 + cont +PR,Providence,P163,320501282112,36415 + cont +PR,0.0,259.70,259.70,...,Providence,Providence,P163320501282112,0.0,0.0,0.0,36415 + cont +pr,P16332050128211236415 + cont +pr,NaN,NaN
3,P161691300317149,Contractual,36415 + cont +PR,Providence,P161,691300317149,36415 + cont +PR,0.0,418.31,418.31,...,Providence,Providence,P161691300317149,0.0,0.0,0.0,36415 + cont +pr,P16169130031714936415 + cont +pr,NaN,NaN
4,P161691300346602,Contractual,36415 + cont +PR,Providence,P161,691300346602,36415 + cont +PR,0.0,300.00,300.00,...,Providence,Providence,P161691300346602,0.0,0.0,0.0,36415 + cont +pr,P16169130034660236415 + cont +pr,NaN,NaN

In [168]:
df_SC_Epic_EI_FC[df_SC_Epic_EI_FC['Key_SC_Epic_EI_FC'].notna()]

,Unique,Drill TYPE,Project Name,FacilityGroupName,FacilityCode,EncounterID,TB Control,Encounter Insurance Balance,EncounterPatientBalance,EncounterOpenBalance,...,Entity Group,Entity,Uni,EncounterInsuranceBalance,Sum of Encounter Insurance Balance_4,Insurance balance diff,PN,Key_y,Key_EI_FC,Key_SC_Epic_EI_FC
663,SDAC514727860,Contractual,Newborn Baby Denial,Sutter Health,SDAC,514727860,Newborn Baby Denial,3661.77,0.0,4258.77,...,Sutter Health,Sutter Health,SDAC514727860,0.00,0.00,3661.77,newborn baby denial,SDAC514727860newborn baby denial,NaN,SDAC514727860
664,SROC514387071,Contractual,Newborn Baby Denial,Sutter Health,SROC,514387071,Newborn Baby Denial,5774.77,0.0,6371.77,...,Sutter Health,Sutter Health,SROC514387071,0.00,0.00,5774.77,newborn baby denial,SROC514387071newborn baby denial,NaN,SROC514387071
665,SROC514460298,Contractual,Newborn Baby Denial,Sutter Health,SROC,514460298,Newborn Baby Denial,4071.48,0.0,4071.48,...,Sutter Health,Sutter Health,SROC514460298,0.00,0.00,4071.48,newborn baby denial,SROC514460298newborn baby denial,NaN,SROC514460298
666,SVSC514401693,Contractual,Newborn Baby Denial,Sutter Health,SVSC,514401693,Newborn Baby Denial,5261.77,0.0,5858.77,...,Sutter Health,Sutter Health,SVSC514401693,0.00,0.00,5261.77,newborn baby denial,SVSC514401693newborn baby denial,NaN,SVSC514401693
667,SVSC514429506,Contractual,Newborn Baby Denial,Sutter Health,SVSC,514429506,Newborn Baby Denial,5674.48,0.0,6271.48,...,Sutter Health,Sutter Health,SVSC514429506,0.00,0.00,5674.48,newborn baby denial,SVSC514429506newborn baby denial,NaN,SVSC514429506
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
136022,P156762001872048,Contractual,Non-Contracted Partial Pays Bucket Level 1,Providence,P156,762001872048,Non-Contracted Partial Pays Bucket Level 1,11199.43,0.0,11199.43,...,Providence,Providence,P156762001872048,4328.04,4328.04,6871.39,non-contracted partial pays bucket level 1,P156762001872048non-contracted partial pays bu...,NaN,P156762001872048
136196,P168550001724713,Contractual,Non-Contracted Partial Pays Bucket Level 1,Providence,P168,550001724713,Non-Contracted Partial Pays Bucket Level 1,6116.08,0.0,6116.08,...,Providence,Providence,P168550001724713,4341.98,4341.98,1774.10,non-contracted partial pays bucket level 1,P168550001724713non-contracted partial pays bu...,NaN,P168550001724713
136206,P173530006928504,Contractual,Non-Contracted Partial Pays Bucket Level 1,Providence,P173,530006928504,Non-Contracted Partial Pays Bucket Level 1,5228.80,0.0,5228.80,...,Providence,Providence,P173530006928504,4777.02,4777.02,451.78,non-contracted partial pays bucket level 1,P173530006928504non-contracted partial pays bu...,NaN,P173530006928504
137616,E14429000187128,Contractual,IH Payment Variance Query 2,Intermountain Health,E144,29000187128,IH Payment Variance Query 2,11198.94,0.0,11198.94,...,IH,IH,E14429000187128,5191.12,5191.12,6007.82,ih payment variance query 2,E14429000187128ih payment variance query 2,NaN,E14429000187128
137941,E37824300013342,Balance Transfer,IH Payment Variance Query 1,NaN,E378,24300013342,IH Payment Variance Query 1,-10453.85,0.0,-10453.85,...,IH,IH,NaN,NaN,NaN,NaN,ih payment variance query 1,E37824300013342ih payment variance query 1,NaN,E37824300013342

In [169]:
df_SC_Epic_EI_FC.columns

Index(['Unique', 'Drill TYPE', 'Project Name', 'FacilityGroupName',
       'FacilityCode', 'EncounterID', 'TB Control',
       'Encounter Insurance Balance', 'EncounterPatientBalance',
       'EncounterOpenBalance',
       ...
       'Entity Group', 'Entity', 'Uni', 'EncounterInsuranceBalance',
       'Sum of Encounter Insurance Balance_4', 'Insurance balance diff', 'PN',
       'Key_y', 'Key_EI_FC', 'Key_SC_Epic_EI_FC'],
      dtype='object', length=139)

# Status Change Epic EI only

In [170]:
file_3 = pd.read_excel(r'C:\Users\IN10052060\Desktop\Status Change Epic\Status Change (Epic).xlsx', sheet_name = 'Sheet2')

In [171]:
file_3['Account ID'] = file_3['Account ID'].apply(
    lambda x: str(int(x)) if pd.notna(x) and x.is_integer() else pd.NA
)

In [172]:
file_3.dropna(subset = 'Account ID', inplace = True)
file_3.shape

(0, 1)

In [173]:
file_3.shape

(0, 1)

In [174]:
file_3['Account ID'] = file_3['Account ID'].astype(str).str.lstrip('0')

In [175]:
file_3.drop_duplicates(subset = 'Account ID', inplace = True)
file_3.shape

(0, 1)

In [176]:
df_SC_Epic_EI = df_SC_Epic_EI_FC.copy()

In [177]:
df_SC_Epic_EI = df_SC_Epic_EI.merge(file_3, left_on = 'EncounterID', right_on = 'Account ID', how = 'left')

In [178]:
df_SC_Epic_EI.head()

,Unique,Drill TYPE,Project Name,FacilityGroupName,FacilityCode,EncounterID,TB Control,Encounter Insurance Balance,EncounterPatientBalance,EncounterOpenBalance,...,Entity,Uni,EncounterInsuranceBalance,Sum of Encounter Insurance Balance_4,Insurance balance diff,PN,Key_y,Key_EI_FC,Key_SC_Epic_EI_FC,Account ID
0,P152271500212924,Contractual,36415 + cont +PR,Providence,P152,271500212924,36415 + cont +PR,0.0,8.91,8.91,...,Providence,P152271500212924,0.0,0.0,0.0,36415 + cont +pr,P15227150021292436415 + cont +pr,NaN,NaN,NaN
1,P152271500215769,Contractual,36415 + cont +PR,Providence,P152,271500215769,36415 + cont +PR,0.0,12.14,12.14,...,Providence,P152271500215769,0.0,0.0,0.0,36415 + cont +pr,P15227150021576936415 + cont +pr,NaN,NaN,NaN
2,P163320501282112,Contractual,36415 + cont +PR,Providence,P163,320501282112,36415 + cont +PR,0.0,259.70,259.70,...,Providence,P163320501282112,0.0,0.0,0.0,36415 + cont +pr,P16332050128211236415 + cont +pr,NaN,NaN,NaN
3,P161691300317149,Contractual,36415 + cont +PR,Providence,P161,691300317149,36415 + cont +PR,0.0,418.31,418.31,...,Providence,P161691300317149,0.0,0.0,0.0,36415 + cont +pr,P16169130031714936415 + cont +pr,NaN,NaN,NaN
4,P161691300346602,Contractual,36415 + cont +PR,Providence,P161,691300346602,36415 + cont +PR,0.0,300.00,300.00,...,Providence,P161691300346602,0.0,0.0,0.0,36415 + cont +pr,P16169130034660236415 + cont +pr,NaN,NaN,NaN

In [179]:
file_4 = pd.read_excel(r'C:\Users\IN10052060\Desktop\Current Bot status\Current Bot Status.xlsx')

In [180]:
file_4['EncounterID'] = file_4['EncounterID'].astype(str).str.lstrip('0')
file_4 = file_4.copy()
file_4['Key_CBS'] = file_4['FacilityCode'].astype(str) + file_4['EncounterID'].astype(str)

In [181]:
file_4.head()

  FacilityCode   EncounterID           Key_CBS
0         A126    1278926939    A1261278926939
1         A129    1281011289    A1291281011289
2         A138    1268003022    A1381268003022
3         A270  1279479233-2  A2701279479233-2
4         A154    1278302576    A1541278302576

In [182]:
file_4.drop_duplicates(subset = 'Key_CBS', inplace = True)

In [183]:
file_4 = file_4[['Key_CBS']]

In [184]:
file_4.shape

(276, 1)

In [185]:
df_CBS = df_SC_Epic_EI.copy()

In [186]:
df_CBS = df_CBS.merge(file_4, left_on = 'Unique', right_on = 'Key_CBS' , how = 'left')

In [187]:
df_completion_status = pd.read_excel(r'C:\Users\IN10052060\Desktop\Completion status\CS.xlsx')

In [188]:
df_completion_status.head()

  FacilityCode EncounterID         CS                TS          FT
0         WMTX  8092267670  Completed  Transacted by TB  Transacted
1         WMTX  8092258981  Completed  Transacted by TB  Transacted
2         WMTX  8092257046  Completed  Transacted by TB  Transacted
3         WMTX  8092256651  Completed  Transacted by TB  Transacted
4         WMTX  8092250033  Completed  Transacted by TB  Transacted

In [189]:
df_completion_status['EncounterID'] = df_completion_status['EncounterID'].astype(str).str.lstrip('0')
df_completion_status = df_completion_status.copy()
df_completion_status['Key_completion_status'] = df_completion_status['FacilityCode'].astype(str) + df_completion_status['EncounterID'].astype(str)

In [190]:
df_completion_status.head()

,FacilityCode,EncounterID,CS,TS,FT,Key_completion_status
0,WMTX,8092267670,Completed,Transacted by TB,Transacted,WMTX8092267670
1,WMTX,8092258981,Completed,Transacted by TB,Transacted,WMTX8092258981
2,WMTX,8092257046,Completed,Transacted by TB,Transacted,WMTX8092257046
3,WMTX,8092256651,Completed,Transacted by TB,Transacted,WMTX8092256651
4,WMTX,8092250033,Completed,Transacted by TB,Transacted,WMTX8092250033

In [191]:
df_completion_status.drop_duplicates(subset = 'Key_completion_status', inplace = True)

In [192]:
df_completion_status = df_completion_status[['CS', 'TS', 'FT', 'Key_completion_status']]

In [193]:
df_completion_status.head()

          CS                TS          FT Key_completion_status
0  Completed  Transacted by TB  Transacted        WMTX8092267670
1  Completed  Transacted by TB  Transacted        WMTX8092258981
2  Completed  Transacted by TB  Transacted        WMTX8092257046
3  Completed  Transacted by TB  Transacted        WMTX8092256651
4  Completed  Transacted by TB  Transacted        WMTX8092250033

In [194]:
completion_status = df_CBS.copy()

In [195]:
completion_status = completion_status.merge(df_completion_status,left_on = 'Unique', right_on = 'Key_completion_status', how = 'left')

In [196]:
completion_status.head()

,Unique,Drill TYPE,Project Name,FacilityGroupName,FacilityCode,EncounterID,TB Control,Encounter Insurance Balance,EncounterPatientBalance,EncounterOpenBalance,...,PN,Key_y,Key_EI_FC,Key_SC_Epic_EI_FC,Account ID,Key_CBS,CS,TS,FT,Key_completion_status
0,P152271500212924,Contractual,36415 + cont +PR,Providence,P152,271500212924,36415 + cont +PR,0.0,8.91,8.91,...,36415 + cont +pr,P15227150021292436415 + cont +pr,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,P152271500215769,Contractual,36415 + cont +PR,Providence,P152,271500215769,36415 + cont +PR,0.0,12.14,12.14,...,36415 + cont +pr,P15227150021576936415 + cont +pr,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,P163320501282112,Contractual,36415 + cont +PR,Providence,P163,320501282112,36415 + cont +PR,0.0,259.70,259.70,...,36415 + cont +pr,P16332050128211236415 + cont +pr,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,P161691300317149,Contractual,36415 + cont +PR,Providence,P161,691300317149,36415 + cont +PR,0.0,418.31,418.31,...,36415 + cont +pr,P16169130031714936415 + cont +pr,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,P161691300346602,Contractual,36415 + cont +PR,Providence,P161,691300346602,36415 + cont +PR,0.0,300.00,300.00,...,36415 + cont +pr,P16169130034660236415 + cont +pr,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [197]:
completion_status.columns

Index(['Unique', 'Drill TYPE', 'Project Name', 'FacilityGroupName',
       'FacilityCode', 'EncounterID', 'TB Control',
       'Encounter Insurance Balance', 'EncounterPatientBalance',
       'EncounterOpenBalance',
       ...
       'PN', 'Key_y', 'Key_EI_FC', 'Key_SC_Epic_EI_FC', 'Account ID',
       'Key_CBS', 'CS', 'TS', 'FT', 'Key_completion_status'],
      dtype='object', length=145)

In [198]:
df = completion_status.copy()

In [199]:

import pandas as pd

df = completion_status.copy()


# Ensure the key input columns exist; if not, create them to avoid KeyErrors.
for col in ['Key_SC_Epic_EI_FC', 'Account ID', 'Key_CBS', 'Key_completion_status',
            'Final Transaction', 'TS', 'CS', 'FT']:
    if col not in df.columns:
        df[col] = pd.NA

# Normalize the "Final Transaction" source column if FT is supposed to mirror "Final Transaction"
# If your 'FT' column is the state you want to use, comment out the line below.
#df['FT'] = df['Final Transaction']

# Pre-create the target columns so .loc assignment works cleanly
for target in ['Tranasction status', 'Completion status', 'Final Transaction']:
    if target not in df.columns:
        df[target] = pd.NA

# ----- Conditions -----
cond_epic_key_notx = df['Key_SC_Epic_EI_FC'].notna() & (df['Final Transaction'] == 'Not Transacted')
cond_account_notx  = df['Account ID'].notna()         & (df['Final Transaction'] == 'Not Transacted')
cond_cbs_tx        = df['Key_CBS'].notna()            & (df['Final Transaction'] == 'Transacted')
cond_key_comp      = df['Key_completion_status'].notna()
penstate = df['Entity Group'] == 'Pennstate'
swedish = df['Entity Group'] == 'Swedish'

# ----- Updates -----
# 1) If Key_SC_Epic_EI_FC present AND FT == 'Not Transacted'
df.loc[cond_epic_key_notx, ['Tranasction status', 'Completion status']] = [
    'EPIC Adj Approval pending', 'EPIC Adj Approval pending'
]

# 2) Else if Account ID present AND FT == 'Not Transacted'
# (Will apply to rows NOT already matched by the first rule automatically due to order)
mask2 = cond_account_notx & ~cond_epic_key_notx
df.loc[mask2, ['Tranasction status', 'Completion status']] = [
    'EPIC Adj Approval pending', 'EPIC Adj Approval pending'
]

# 3) Else if Key_CBS present AND FT == 'Transacted'
df.loc[cond_cbs_tx, ['Tranasction status', 'Completion status']] = [
    'Transacted by BOT', 'Completed'
]

# 4) Else if Key_completion_status present → copy TS/CS/FT into outputs
mask4 = cond_key_comp & ~cond_epic_key_notx & ~mask2 & ~cond_cbs_tx
df.loc[mask4, 'Tranasction status'] = df.loc[mask4, 'TS']
df.loc[mask4, 'Completion status']   = df.loc[mask4, 'CS']
df.loc[mask4, 'Final Transaction']   = df.loc[mask4, 'FT']

#5)
mask5 = swedish
df.loc[mask5, ['Completion status', 'Tranasction status', 'Final Transaction']] = ['Pending with Ops', 'Not worked not transacted', 'Not Transacted']


# Everything else is left unchanged.

In [200]:
penstate = df[df['Entity Group'] == 'Pennstate']

In [201]:
df['Entity Group'].unique()

array(['Providence', 'Ascension', 'EBO', 'Lifepoint', 'Quorum',
       'Pennstate', 'IH', 'Swedish', 'Sutter Health', 'No Volume', nan,
       'Out of scope'], dtype=object)

In [202]:
df[df['Unique'] == 'VPKSV00031620370']

Empty DataFrame
Columns: [Unique, Drill TYPE, Project Name, FacilityGroupName, FacilityCode, EncounterID, TB Control, Encounter Insurance Balance, EncounterPatientBalance, EncounterOpenBalance, WRITEOFF, AdmitDate, DischargeDate, Encounter Patient Balance, Encounter Open Balance, Username, ActivityCode, Work Allocation, Metric 7 site, Ageing category, $ category, IMH, LP 90+, LP 180+, 7A, 7B, Actual Txn $, Tranascted (Yes/No), Bot upload, EncounterID2, Unique2, BOT status, Assigned to, TB assignment, TB status, TB reason, TB productivity, Status1, Skip/fail, Completion status, Tranasction status, KPI Cluster, Drill Code, Drill Name, CF amt $, Drill Type No, Final Transaction, CF Category, Date, Assignment, Primary Payer Plan Code, Secondary Payer Plan Code, Primary Payer Plan Name, Primary Patient responsibility, Secondary Payer Plan Name, Current Payer Plan Code, Tertiary Payer Plan Code, Primary Major Payor, Secondary Major Payor, Tertiary Major Payor, Current Major Payor, StandardPatientType, CF validation, BOT site, BOT capacity, BOT credentials, Exclusionlist, SuperUnique, Emp ID, Status, Final Status, Current Balance, Transacted $, Phase, DFD, Repetitive, EncounterTotalCharges, dsfd, Check, Claim Status, Repititive_Week2, Repititive, Actual repetitive, Repititive/fresh, Mass update, Next Follow Date, InvoiceNumber, Grp_Cd1, Rsn_Cd1, Amt1, Grp_Cd2, Rsn_Cd2, Amt2, Grp_Cd3, Rsn_Cd3, Amt3, Grp_Cd4, Rsn_Cd4, Amt4, Grp_Cd5, ...]
Index: []

[0 rows x 145 columns]

In [203]:
df.shape

(137950, 145)

In [204]:
df[df['Entity Group'] == 'Pennstate']['Final Transaction'].unique()

array(['Not Transacted', 'Transacted'], dtype=object)

In [205]:
df.columns

Index(['Unique', 'Drill TYPE', 'Project Name', 'FacilityGroupName',
       'FacilityCode', 'EncounterID', 'TB Control',
       'Encounter Insurance Balance', 'EncounterPatientBalance',
       'EncounterOpenBalance',
       ...
       'PN', 'Key_y', 'Key_EI_FC', 'Key_SC_Epic_EI_FC', 'Account ID',
       'Key_CBS', 'CS', 'TS', 'FT', 'Key_completion_status'],
      dtype='object', length=145)

In [207]:
start_time = time.time()

TB_control = pd.read_excel(
    r"C:\Users\IN10052060\Desktop\TB Control Grid_Master List.xlsx",
    sheet_name='TB Control Grid_Master List'
)

end_time = time.time()
elapsed_time = end_time - start_time

print(f"File loaded in {elapsed_time:.2f} seconds")

File loaded in 0.14 seconds

In [208]:
TB_control['DC'] = TB_control['Drill Code'].str.strip().str.lower()

In [209]:
TB_control = TB_control[['DC']]

In [210]:
df = df.merge(TB_control, left_on = 'PN', right_on = 'DC', how = 'left')

In [211]:
df['PN']

0                    36415 + cont +pr
1                    36415 + cont +pr
2                    36415 + cont +pr
3                    36415 + cont +pr
4                    36415 + cont +pr
                     ...
137945    ih payment variance query 4
137946    ih payment variance query 4
137947    ih payment variance query 4
137948    ih payment variance query 4
137949    ih payment variance query 4
Name: PN, Length: 137950, dtype: object

In [212]:
df[['DC_x', 'DC_y']]

                               DC_x                         DC_y
0                  36415 + cont +PR             36415 + cont +pr
1                  36415 + cont +PR             36415 + cont +pr
2                  36415 + cont +PR             36415 + cont +pr
3                  36415 + cont +PR             36415 + cont +pr
4                  36415 + cont +PR             36415 + cont +pr
...                             ...                          ...
137945  IH Payment Variance Query 4  ih payment variance query 4
137946  IH Payment Variance Query 4  ih payment variance query 4
137947  IH Payment Variance Query 4  ih payment variance query 4
137948  IH Payment Variance Query 4  ih payment variance query 4
137949  IH Payment Variance Query 4  ih payment variance query 4

[137950 rows x 2 columns]

In [213]:
df['Drill Status'] = np.where( df['DC_y'].isna(), "Adhoc", "Regular")

In [214]:
df['Drill Status']

0         Regular
1         Regular
2         Regular
3         Regular
4         Regular
           ...
137945    Regular
137946    Regular
137947    Regular
137948    Regular
137949    Regular
Name: Drill Status, Length: 137950, dtype: object

In [215]:
df.columns

Index(['Unique', 'Drill TYPE', 'Project Name', 'FacilityGroupName',
       'FacilityCode', 'EncounterID', 'TB Control',
       'Encounter Insurance Balance', 'EncounterPatientBalance',
       'EncounterOpenBalance',
       ...
       'Key_y', 'Key_EI_FC', 'Key_SC_Epic_EI_FC', 'Account ID', 'Key_CBS',
       'CS', 'TS', 'FT', 'Key_completion_status', 'DC_y'],
      dtype='object', length=146)

In [216]:
import os
import time
import pandas as pd
from openpyxl import Workbook, load_workbook

start_time = time.time()

file_path = r'C:\Users\IN10052060\OneDrive - R1\Target Balance support\Final Last week.xlsx'

# Step 1: Check if file exists, delete if yes
if os.path.exists(file_path):
    os.remove(file_path)
    print("🗑️ Existing file deleted.")

# Step 2: Create a fresh Excel file
wb = Workbook()
wb.save(file_path)
print("📂 New Excel file created.")

# Step 3: Export your DataFrame to the new file
with pd.ExcelWriter(file_path, engine='openpyxl', mode='a') as writer:
    df.to_excel(writer, sheet_name = 'Sheet1',index=False)

end_time = time.time()
elapsed_time = end_time - start_time

print(f"✅ Data successfully written to the sheet in {elapsed_time:.2f} seconds")

🗑️ Existing file deleted.
📂 New Excel file created.
✅ Data successfully written to the sheet in 365.47 seconds

In [217]:
df.shape

(137950, 146)